-- Maya B037 professional paid-marketing capability staging.
-- Existing B036 capabilities remain enabled. New B037 capabilities stay PLANNED until
-- approved brand facts + live creative/video providers + paid-media connections are certified.

with maya as (select id from public.ai_employees where code='marketing_manager' limit 1),
capability_data(capability_key,capability_label,capability_description,execution_mode,requires_human_approval,status) as (
  values
    ('live_marketing_read','Live Marketing Read','Maya B037 capability: Live Marketing Read.','read',false,'enabled'),
    ('approved_brand_fact_gate','Approved Brand Fact Gate','Maya B037 capability: Approved Brand Fact Gate.','analyze',false,'enabled'),
    ('prohibited_claim_guard','Prohibited Claim Guard','Maya B037 capability: Prohibited Claim Guard.','analyze',false,'enabled'),
    ('brand_profile_status_awareness','Brand Profile Status Awareness','Maya B037 capability: Brand Profile Status Awareness.','read',false,'enabled'),
    ('platform_profile_awareness','Platform Profile Awareness','Maya B037 capability: Platform Profile Awareness.','read',false,'enabled'),
    ('social_connection_health','Social Connection Health','Maya B037 capability: Social Connection Health.','read',false,'enabled'),
    ('publish_job_health','Publish Job Health','Maya B037 capability: Publish Job Health.','read',false,'enabled'),
    ('marketing_post_queue','Marketing Post Queue','Maya B037 capability: Marketing Post Queue.','read',false,'enabled'),
    ('media_library_awareness','Media Library Awareness','Maya B037 capability: Media Library Awareness.','read',false,'enabled'),
    ('platform_specific_drafting','Platform Specific Drafting','Maya B037 capability: Platform Specific Drafting.','generate',false,'enabled'),
    ('campaign_concept_generation','Campaign Concept Generation','Maya B037 capability: Campaign Concept Generation.','generate',false,'enabled'),
    ('content_calendar_planning','Content Calendar Planning','Maya B037 capability: Content Calendar Planning.','generate',false,'enabled'),
    ('draft_save_only','Draft Save Only','Maya B037 capability: Draft Save Only.','write_internal',false,'enabled'),
    ('approval_readiness_check','Approval Readiness Check','Maya B037 capability: Approval Readiness Check.','analyze',false,'enabled'),
    ('no_self_approval','No Self Approval','Maya B037 capability: No Self Approval.','analyze',false,'enabled'),
    ('external_publish_boundary','External Publish Boundary','Maya B037 capability: External Publish Boundary.','analyze',true,'enabled'),
    ('oauth_token_boundary','Oauth Token Boundary','Maya B037 capability: Oauth Token Boundary.','analyze',false,'enabled'),
    ('unsupported_claim_detection','Unsupported Claim Detection','Maya B037 capability: Unsupported Claim Detection.','analyze',false,'enabled'),
    ('blocked_work_explanation','Blocked Work Explanation','Maya B037 capability: Blocked Work Explanation.','analyze',false,'enabled'),
    ('assignment_execution','Assignment Execution','Maya B037 capability: Assignment Execution.','generate',false,'enabled'),
    ('delivery_health_review','Delivery Health Review','Maya B037 capability: Delivery Health Review.','track',false,'enabled'),
    ('escalation_path','Escalation Path','Maya B037 capability: Escalation Path.','delegate',false,'enabled'),
    ('duplicate_draft_prevention','Duplicate Draft Prevention','Maya B037 capability: Duplicate Draft Prevention.','track',false,'enabled'),
    ('kpi_recording','Kpi Recording','Maya B037 capability: Kpi Recording.','track',false,'enabled'),
    ('supervised_learning','Supervised Learning','Maya B037 capability: Supervised Learning.','generate',false,'enabled'),
    ('owner_feedback_learning','Owner Feedback Learning','Maya B037 capability: Owner Feedback Learning.','generate',false,'enabled'),
    ('ad_copy_short_form','Ad Copy Short Form','Maya B037 capability: Ad Copy Short Form.','generate',false,'planned'),
    ('ad_copy_long_form','Ad Copy Long Form','Maya B037 capability: Ad Copy Long Form.','generate',false,'planned'),
    ('headline_generation','Headline Generation','Maya B037 capability: Headline Generation.','generate',false,'planned'),
    ('primary_text_generation','Primary Text Generation','Maya B037 capability: Primary Text Generation.','generate',false,'planned'),
    ('description_cta_generation','Description CTA Generation','Maya B037 capability: Description CTA Generation.','generate',false,'planned'),
    ('platform_ad_variant_generation','Platform Ad Variant Generation','Maya B037 capability: Platform Ad Variant Generation.','generate',false,'planned'),
    ('creative_brief_generation','Creative Brief Generation','Maya B037 capability: Creative Brief Generation.','generate',false,'planned'),
    ('image_generation','Image Generation','Maya B037 capability: Image Generation.','generate',false,'planned'),
    ('image_aspect_ratio_variants','Image Aspect Ratio Variants','Maya B037 capability: Image Aspect Ratio Variants.','generate',false,'planned'),
    ('thumbnail_generation','Thumbnail Generation','Maya B037 capability: Thumbnail Generation.','generate',false,'planned'),
    ('video_script_generation','Video Script Generation','Maya B037 capability: Video Script Generation.','generate',false,'planned'),
    ('storyboard_generation','Storyboard Generation','Maya B037 capability: Storyboard Generation.','generate',false,'planned'),
    ('short_video_generation','Short Video Generation','Maya B037 capability: Short Video Generation.','generate',false,'planned'),
    ('voiceover_generation','Voiceover Generation','Maya B037 capability: Voiceover Generation.','generate',false,'planned'),
    ('captions_generation','Captions Generation','Maya B037 capability: Captions Generation.','generate',false,'planned'),
    ('video_scene_generation','Video Scene Generation','Maya B037 capability: Video Scene Generation.','generate',false,'planned'),
    ('video_asset_sync','Video Asset Sync','Maya B037 capability: Video Asset Sync.','track',false,'planned'),
    ('long_video_production_package','Long Video Production Package','Maya B037 capability: Long Video Production Package.','generate',false,'planned'),
    ('creative_asset_draft_storage','Creative Asset Draft Storage','Maya B037 capability: Creative Asset Draft Storage.','write_internal',false,'planned'),
    ('provider_readiness_awareness','Provider Readiness Awareness','Maya B037 capability: Provider Readiness Awareness.','read',false,'planned'),
    ('video_editor_handoff','Video Editor Handoff','Maya B037 capability: Video Editor Handoff.','delegate',false,'planned'),
    ('paid_media_account_readiness','Paid Media Account Readiness','Maya B037 capability: Paid Media Account Readiness.','read',false,'planned'),
    ('audience_messaging_plan','Audience Messaging Plan','Maya B037 capability: Audience Messaging Plan.','generate',false,'planned'),
    ('targeting_brief_generation','Targeting Brief Generation','Maya B037 capability: Targeting Brief Generation.','generate',false,'planned'),
    ('conversion_tracking_plan','Conversion Tracking Plan','Maya B037 capability: Conversion Tracking Plan.','generate',false,'planned'),
    ('ab_test_plan_generation','AB Test Plan Generation','Maya B037 capability: AB Test Plan Generation.','generate',false,'planned'),
    ('landing_page_copy_generation','Landing Page Copy Generation','Maya B037 capability: Landing Page Copy Generation.','generate',false,'planned'),
    ('campaign_draft_package','Campaign Draft Package','Maya B037 capability: Campaign Draft Package.','generate',false,'planned'),
    ('utm_tracking_plan','UTM Tracking Plan','Maya B037 capability: UTM Tracking Plan.','generate',false,'planned'),
    ('creative_spec_adaptation','Creative Spec Adaptation','Maya B037 capability: Creative Spec Adaptation.','generate',false,'planned'),
    ('no_budget_spend_boundary','No Budget Spend Boundary','Maya B037 capability: No Budget Spend Boundary.','analyze',true,'planned'),
    ('no_ad_launch_boundary','No Ad Launch Boundary','Maya B037 capability: No Ad Launch Boundary.','analyze',true,'planned'),
    ('no_campaign_activation_boundary','No Campaign Activation Boundary','Maya B037 capability: No Campaign Activation Boundary.','analyze',true,'planned')
)
insert into public.ai_employee_capabilities
(ai_employee_id,capability_key,capability_label,capability_description,execution_mode,requires_human_approval,status,endpoint,version,updated_at)
select maya.id,c.capability_key,c.capability_label,c.capability_description,c.execution_mode,c.requires_human_approval,c.status,'ai-maya-marketing-manager','2',now()
from maya cross join capability_data c
on conflict (ai_employee_id,capability_key) do update set
  capability_label=excluded.capability_label,
  capability_description=excluded.capability_description,
  execution_mode=excluded.execution_mode,
  requires_human_approval=excluded.requires_human_approval,
  status=excluded.status,
  endpoint=excluded.endpoint,
  version=excluded.version,
  updated_at=now();
