window.ALLSHIELD_BUILD_INFO={
  build_number:'B2026.08.23.021',
  base_build:'B2026.08.23.021',
  current_build:'B2026.08.28.035',
  label:'Production B035 — Olivia AI Operations Manager Live Execution — Certified',
  completion_release:'2026.08.28.020',
  channel:'production',
  released_at:'2026-08-28',
  certification:{
    olivia_operations_manager:'LIVE WORK PASS',
    olivia_capabilities:'27/27 PASS',
    olivia_runtime_contract:'21/21 PASS',
    olivia_duplicate_suppression:'LIVE TWO-RUN PASS',
    olivia_execution_engine:'PRODUCTION ACTIVE — PROVIDER-INDEPENDENT',
    olivia_owner_workforce:'PASS',
    olivia_browser_smoke:'DESKTOP + MOBILE PASS',
    avery_chief_of_staff:'LIVE WORK PASS',
    avery_capabilities:'8/8 PASS',
    avery_runtime_contract:'22/22 PASS',
    avery_execution_engine:'PRODUCTION ACTIVE — PROVIDER-INDEPENDENT',
    ai_workforce_organization:'31/31 PASS',
    ai_workforce_learning:'PASS',
    ai_workforce_database:'PASS',
    document_esign_cors:'14/14 PASS',
    dashboard_tile_routing:'31/31 PASS',
    dashboard_count_integrity:'PASS',
    agent_operations:'61/61 PASS',
    onboarding:'31/31 PASS',
    esign:'28/28 PASS',
    careers_professional_video:'PASS',
    pages:'PASS',
    owner_portal:'PASS',
    database_security:'PASS'
  },
  changes:[
    'Certified Olivia as a real AI Operations Manager only after a live production execution and dedicated regression gates passed',
    'Invalidated the earlier premature B035 pass and restored B034 until Olivia met the full Operations Manager standard',
    'Rebuilt Olivia on the canonical Master Agent Profile model rather than creating a competing operations record system',
    'Expanded Olivia to 27 exercised capabilities across onboarding, careers conversion, licensing, Academy, E-Sign, contracting, lifecycle, production readiness, meetings, communications, administrative queues, prioritization, delegation, follow-up, escalation, briefing, KPIs, learning and authorization boundaries',
    'Olivia completed a real production scan and detected five current operational exceptions without fabricating any issues',
    'The live scan identified aging and incomplete onboarding as high priority and created two tracked Avery escalation jobs',
    'A second consecutive live scan created zero new escalations and suppressed both existing routing keys as duplicates',
    'Found and repaired the real ai_jobs requester defect in Olivia escalation creation while preserving the existing NOT NULL database constraint',
    'Added a permanent Olivia source-contract gate covering all 27 capabilities, canonical Master Agent Profile linkage, tracked routing and follow-through, supervised-learning wiring, protected-action boundaries and Owner AI Workforce display',
    'Verified the Owner AI Workforce remains database-backed for Olivia identity, reporting structure, job assignment, KPIs, work history, scorecard, feedback and learning status',
    'No Owner-approved Olivia lesson existed during certification, so zero lessons were fabricated or falsely claimed as reused; the approved teach-and-reuse path remains enabled',
    'Production browser smoke passed against allshieldinsurancegroup.com at desktop and mobile sizes with critical AI Workforce and build assets present and no detected ReferenceError, TypeError or SyntaxError',
    'Retired the temporary Olivia certification runner and one-off certification workflows after evidence was permanently recorded',
    'Preserved human approval boundaries for termination, compensation, production credit, exam results, regulated licensing facts, signatures, banking, security roles, permissions and external publishing',
    'Retained the approved B2026.08.23.021 baseline and prior certified Avery, dashboard, onboarding, Agent Operations, E-Sign, Careers, communications, Academy, Video Studio, mobile and desktop behavior'
  ]
};