window.ALLSHIELD_BUILD_INFO={
  build_number:'B2026.08.23.021',
  base_build:'B2026.08.23.021',
  current_build:'B2026.08.28.036',
  label:'Production B036 — Maya AI Marketing Manager Live Execution — Certified',
  completion_release:'2026.08.28.021',
  channel:'production',
  released_at:'2026-08-28',
  certification:{
    maya_marketing_manager:'LIVE WORK PASS',
    maya_capabilities:'26/26 PASS',
    maya_source_contract:'24/24 PASS',
    maya_runtime_contract:'12/12 PASS',
    maya_certification_registry:'24/24 PASS',
    maya_brand_safety:'APPROVED-FACT FAIL-CLOSED PASS',
    maya_live_delivery_review:'12 CHANNEL BLOCKERS VERIFIED',
    maya_external_publish_boundary:'PASS',
    maya_owner_workforce:'PASS',
    maya_browser_smoke:'DESKTOP + MOBILE PASS',
    olivia_operations_manager:'LIVE WORK PASS',
    olivia_capabilities:'27/27 PASS',
    olivia_runtime_contract:'21/21 PASS',
    olivia_duplicate_suppression:'LIVE TWO-RUN PASS',
    olivia_execution_engine:'PRODUCTION ACTIVE — PROVIDER-INDEPENDENT',
    olivia_owner_workforce:'PASS',
    olivia_browser_smoke:'DESKTOP + MOBILE PASS',
    avery_chief_of_staff:'LIVE WORK PASS',
    avery_capabilities:'8/8 PASS',
    avery_runtime_contract:'22/22 PASS',
    avery_execution_engine:'PRODUCTION ACTIVE — PROVIDER-INDEPENDENT',
    ai_workforce_organization:'31/31 PASS',
    ai_workforce_learning:'PASS',
    ai_workforce_database:'PASS',
    document_esign_cors:'14/14 PASS',
    dashboard_tile_routing:'31/31 PASS',
    dashboard_count_integrity:'PASS',
    agent_operations:'61/61 PASS',
    onboarding:'31/31 PASS',
    esign:'28/28 PASS',
    careers_professional_video:'PASS',
    pages:'PASS',
    owner_portal:'PASS',
    database_security:'PASS'
  },
  changes:[
    'Certified Maya as the real AI Marketing Manager after executing an existing Avery-assigned production marketing health job and passing dedicated source, live and browser certification gates',
    'Added Maya dedicated production execution through ai-maya-marketing-manager and routed Owner AI Workforce marketing work to that engine in runtime 2026.08.28.007',
    'Registered 26 Maya capabilities covering approved brand facts, platform profiles, social connection health, publish-job health, marketing queues, media, platform drafting, campaigns, calendars, draft-only storage, approval readiness, escalation, KPIs and supervised learning',
    'Maya live work found the primary ALLSHIELD brand profile still in draft with zero approved facts and correctly failed closed instead of inventing or treating draft claims as approved marketing facts',
    'Maya verified all 12 configured social channels are currently not connected and reported them as real delivery blockers without reading, changing or exposing OAuth tokens',
    'The real Maya run prepared zero drafts, saved zero posts and made zero publish attempts because the approved-brand prerequisite was not satisfied',
    'Maya created one tracked Avery escalation for the unapproved brand profile while avoiding a redundant connection-health escalation because that work already originated from Avery',
    'Preserved hard boundaries preventing Maya from self-approving brand or platform profiles, approving posts, publishing or scheduling externally, retrying publish jobs, changing OAuth credentials or bypassing Owner/Admin approval',
    'Maya creative generation is approved-fact-only with prohibited-claim checks, duplicate-draft suppression and a deterministic safe fallback when an external model provider is unavailable',
    'Recorded 24 permanent B036 certification rows as PASS from real evidence; no Maya learning lesson existed at certification, so zero lessons were fabricated or falsely claimed',
    'Maya permanent source contract passed 24/24 and live production contract passed 12/12, including CORS, unauthorized-access rejection and live runtime routing',
    'Independent desktop and mobile browser smoke passed on the live site with the Maya-aware .007 runtime loaded and no detected ReferenceError, TypeError or SyntaxError',
    'Retired the temporary Maya certification runner and removed the one-time routing and browser-smoke workflows after permanent evidence was recorded',
    'Final B036 cross-employee release gate requires Maya, Olivia and Avery certifications to remain valid together under the current 2026.08.28.007 AI Workforce runtime and B036 production metadata',
    'Retained the approved B2026.08.23.021 baseline and all prior certified Avery, Olivia, dashboard, onboarding, Agent Operations, E-Sign, Careers, communications, Academy, Video Studio, mobile and desktop behavior'
  ]
};