window.ALLSHIELD_BUILD_INFO={
  build_number:'B2026.08.23.021',
  base_build:'B2026.08.23.021',
  current_build:'B2026.08.29.045',
  label:'B045 Candidate — Professional Social Provider Verification',
  completion_release:'2026.08.28.021',
  channel:'production',
  released_at:'2026-08-29',
  certification:{
    social_connection_center:'PASS',
    social_provider_vault:'PASS',
    social_professional_verification:'PASS',
    social_identity_verification:'PASS',
    social_permission_matrix:'PASS',
    social_comment_permission_gate:'PASS',
    social_browser_secret_exposure:'0 SECRETS RETURNED',
    maya_core_social_readiness:'LIVE VERIFIED STATE',
    victor_video_editor:'CORE LIVE WORK PASS — PROFESSIONAL COMPLETION BLOCKED',
    victor_core_capabilities:'39/39 PASS',
    victor_provider_capabilities:'6 PLANNED — PROVIDERS REQUIRED',
    victor_real_work:'AVERY MEDIA READINESS JOB PASS',
    victor_protected_boundaries:'403 PASS',
    victor_external_provider_readiness:'INCOMPLETE',
    video_studio_provider_gateway:'PASS',
    video_studio_legacy_sora_removed:'PASS',
    living_compensation_contracts:'PASS',
    contract_section_auto_sync:'PASS',
    residual_section_removal:'PASS',
    versioned_contract_reacceptance:'PASS',
    universal_compensation:'LIVE CONFIGURATION PASS',
    editable_commission_structure:'PASS',
    editable_bonus_structure:'PASS',
    editable_agent_tiers:'PASS',
    product_program_reuse:'PASS',
    automatic_bonus_qualification_tracking:'PASS',
    marcus_performance_analyst:'LIVE WORK PASS',
    marcus_capabilities:'34/34 PASS',
    marcus_runtime_contract:'STAGING + PRODUCTION PASS',
    marcus_real_data_only:'PASS',
    marcus_duplicate_suppression:'LIVE MULTI-RUN PASS',
    marcus_protected_boundaries:'403 PASS',
    marcus_execution_engine:'PRODUCTION ACTIVE — PROVIDER-INDEPENDENT',
    maya_marketing_manager:'LIVE WORK PASS',
    maya_capabilities:'26/26 PASS',
    maya_source_contract:'24/24 PASS',
    maya_runtime_contract:'12/12 PASS',
    maya_certification_registry:'24/24 PASS',
    maya_brand_safety:'APPROVED-FACT FAIL-CLOSED PASS',
    maya_live_delivery_review:'12 CHANNEL BLOCKERS VERIFIED',
    maya_external_publish_boundary:'PASS',
    maya_owner_workforce:'PASS',
    maya_browser_smoke:'DESKTOP + MOBILE PASS',
    olivia_operations_manager:'LIVE WORK PASS',
    olivia_capabilities:'27/27 PASS',
    olivia_runtime_contract:'21/21 PASS',
    olivia_duplicate_suppression:'LIVE TWO-RUN PASS',
    olivia_execution_engine:'PRODUCTION ACTIVE — PROVIDER-INDEPENDENT',
    olivia_owner_workforce:'PASS',
    olivia_browser_smoke:'DESKTOP + MOBILE PASS',
    avery_chief_of_staff:'LIVE WORK PASS',
    avery_capabilities:'8/8 PASS',
    avery_runtime_contract:'22/22 PASS',
    avery_execution_engine:'PRODUCTION ACTIVE — PROVIDER-INDEPENDENT',
    ai_workforce_organization:'31/31 PASS',
    ai_workforce_learning:'PASS',
    ai_workforce_database:'PASS',
    document_esign_cors:'14/14 PASS',
    dashboard_tile_routing:'31/31 PASS',
    dashboard_count_integrity:'PASS',
    agent_operations:'61/61 PASS',
    onboarding:'31/31 PASS',
    esign:'28/28 PASS',
    careers_professional_video:'PASS',
    pages:'PASS',
    owner_portal:'PASS',
    database_security:'PASS'
  },
  changes:[
    'Added a dedicated Owner/Admin Social Connection Center with secure provider credential entry, OAuth launch, account identity verification, token-health verification and professional capability checks before Maya or Victor can treat an account as operational',
    'Provider developer credentials entered in the back office are encrypted in Supabase Vault through service-role-only database functions; decrypted secret values are never returned to browser clients',
    'Added live verification evidence for publishing, engagement-read, comment-read and comment-reply permissions where Allshield has certified platform support, including missing-scope reporting and a Maya core social readiness gate',
    'Expanded Meta connection requirements to include Facebook Page community permissions and Instagram professional comment management permissions; added TikTok creator-info verification and YouTube upload/comment scope verification',
    'Added Victor dedicated AI Media & Video Producer execution with 39 enabled core capabilities, 6 provider-dependent capabilities held planned, real-media-only evidence, tracked work, repurposing packages and protected publish/OAuth/delete boundaries',
    'Victor completed Avery’s real media delivery readiness assignment against the existing Careers video, detected YouTube and provider blockers, generated a real production/repurpose package from stored script/storyboard data, and created three tracked Avery escalations',
    'Modernized Video Studio to GPT-5.6 Sol, GPT-Image-2, GPT-4o-mini-TTS and a provider-independent durable video gateway; removed direct use of the deprecated Sora video endpoint',
    'Added living compensation agreements generated directly from each compensation version; base rates, bonuses, tiers, leadership rules, residuals and program terms now drive the current agreement automatically',
    'Removing residuals from a draft clears that version residual split configuration, blocks residual calculations and removes the entire Residuals section and residual clauses from the generated agreement',
    'Previously published and accepted agreements remain immutable; each newly published compensation version creates a new agreement and pending acceptance requirement for assigned agents',
    'Added universal versioned compensation configuration for ACA and future products/programs, including editable base commission, bonus structures, agent tiers and automatic qualification snapshots',
    'Certified Marcus as the AI Performance & Compensation Analyst after real staging and production execution against current ALLSHIELD configuration and data',
    'Registered 34 Marcus capabilities for verified production, enrollment, compensation, payroll and promotion analysis with recommendation-only protected boundaries',
    'Marcus correctly detected the active ACA campaign compensation plan remains draft and the stored manager coaching 50/$50 rule conflicts with the approved 200/$50 framework without modifying either record',
    'Marcus created three tracked Avery escalations on the first live scan and suppressed all duplicate escalations on repeated staging, work and production scans',
    'Marcus produced zero fabricated coaching recommendations or emerging-leader claims because live production, enrollment, payroll and promotion snapshot sources are currently empty',
    'Protected compensation, payroll, promotion and agent-status mutation actions returned 403 and the temporary certification runner was retired',
    'Certified Maya as the real AI Marketing Manager after executing an existing Avery-assigned production marketing health job and passing dedicated source, live and browser certification gates',
    'Added Maya dedicated production execution through ai-maya-marketing-manager and routed Owner AI Workforce marketing work to that engine in runtime 2026.08.28.007',
    'Registered 26 Maya capabilities covering approved brand facts, platform profiles, social connection health, publish-job health, marketing queues, media, platform drafting, campaigns, calendars, draft-only storage, approval readiness, escalation, KPIs and supervised learning',
    'Maya live work found the primary ALLSHIELD brand profile still in draft with zero approved facts and correctly failed closed instead of inventing or treating draft claims as approved marketing facts',
    'Maya verified all 12 configured social channels are currently not connected and reported them as real delivery blockers without reading, changing or exposing OAuth tokens',
    'The real Maya run prepared zero drafts, saved zero posts and made zero publish attempts because the approved-brand prerequisite was not satisfied',
    'Maya created one tracked Avery escalation for the unapproved brand profile while avoiding a redundant connection-health escalation because that work already originated from Avery',
    'Preserved hard boundaries preventing Maya from self-approving brand or platform profiles, approving posts, publishing or scheduling externally, retrying publish jobs, changing OAuth credentials or bypassing Owner/Admin approval',
    'Maya creative generation is approved-fact-only with prohibited-claim checks, duplicate-draft suppression and a deterministic safe fallback when an external model provider is unavailable',
    'Recorded 24 permanent B036 certification rows as PASS from real evidence; no Maya learning lesson existed at certification, so zero lessons were fabricated or falsely claimed',
    'Maya permanent source contract passed 24/24 and live production contract passed 12/12, including CORS, unauthorized-access rejection and live runtime routing',
    'Independent desktop and mobile browser smoke passed on the live site with the Maya-aware .007 runtime loaded and no detected ReferenceError, TypeError or SyntaxError',
    'Retired the temporary Maya certification runner and removed the one-time routing and browser-smoke workflows after permanent evidence was recorded',
    'Retained the approved B2026.08.23.021 baseline and all prior certified Avery, Olivia, dashboard, onboarding, Agent Operations, E-Sign, Careers, communications, Academy, Video Studio, mobile and desktop behavior'
  ]
};