(() => {
 const sb=window.allshieldSupabase; if(!sb)return;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function current(){const u=(await sb.auth.getUser()).data.user;if(!u)return null;const {data:p}=await sb.from('profiles').select('id,first_name,last_name,role,resident_state,status').eq('id',u.id).single();return p}
 async function ensureMarket(p){if(!p?.resident_state||!['GA','TX','FL','TN'].includes(p.resident_state))return;const state=p.resident_state;const marketplace=state==='GA'?'Georgia Access':'CMS FFM';const training_url=state==='GA'?'https://georgiaaccess.gov/agents':'https://portal.cms.gov';await sb.from('marketplace_certifications').upsert({user_id:p.id,state_code:state,marketplace,plan_year:2027,status:'not_started',training_url,metadata:{annual:true,required_for_aca_ready:true}},{onConflict:'user_id,state_code,plan_year',ignoreDuplicates:true});}
 async function render(){const p=await current();if(!p)return;await ensureMarket(p);if(!['agent','team_lead','manager'].includes(p.role))return;const state=p.resident_state;if(!['GA','TX','FL','TN'].includes(state||''))return;
 const [{data:track},{data:bp},{data:course},{data:market},{data:sessions},{data:license}]=await Promise.all([
 sb.from('academy_launch_tracks').select('*').eq('state_code',state).maybeSingle(),sb.from('exam_blueprints').select('*').eq('state_code',state).eq('status','active').order('version',{ascending:false}).limit(1).maybeSingle(),sb.from('courses').select('id,title,status').eq('state_code',state).eq('category','state_exam_prep').eq('status','published').limit(1).maybeSingle(),sb.from('marketplace_certifications').select('*').eq('user_id',p.id).eq('state_code',state).order('plan_year',{ascending:false}).limit(1).maybeSingle(),sb.from('exam_sessions').select('mode,score_percent,passed,completed_at,weak_topics').eq('user_id',p.id).eq('state_code',state).order('completed_at',{ascending:false}).limit(5),sb.from('user_state_licenses').select('*').eq('user_id',p.id).eq('state_code',state).limit(1).maybeSingle()]);
 const sections=Array.isArray(bp?.sections)?bp.sections:[];const fullPass=(sessions||[]).some(x=>x.mode==='full'&&x.passed);const licensed=['active','licensed'].includes(String(license?.status||''));const marketOK=market?.status==='verified';const acaReady=licensed&&marketOK;
 const html=`<div class="card" style="margin-top:18px"><div class="eyebrow">LAUNCH ACADEMY · ${esc(state)}</div><h3>${esc(course?.title||'State Licensing Academy')}</h3><p>Your launch path is tracked separately for state licensing and ACA Marketplace authorization.</p><div class="grid3"><div class="stat"><b>${esc(bp?.version||'—')}</b><span>Blueprint version</span></div><div class="stat"><b>${fullPass?'Passed':'In progress'}</b><span>Full simulation</span></div><div class="stat"><b>${acaReady?'READY':'NOT READY'}</b><span>ACA Dialer status</span></div></div><h4>Official exam map</h4>${sections.map(s=>`<div class="row"><b>${esc(s.label||s.title||s.key)}</b>${s.weight?`<span>${esc(s.weight)} outline weight</span>`:''}</div>`).join('')||'<p>Blueprint mapping is being validated.</p>'}<h4>Marketplace certification</h4><div class="row"><div><b>${esc(market?.marketplace||track?.marketplace_type||'Marketplace')}</b><div>Plan Year ${esc(market?.plan_year||2027)} · ${esc(market?.status||'not started')}</div></div><a class="btn secondary" href="${esc(market?.training_url||track?.marketplace_url||'#')}" target="_blank" rel="noopener">Open official portal</a></div><p class="small">Allshield never stores your Marketplace password or MFA. Completion is tracked separately from your state license.</p><h4>Recent exam performance</h4>${(sessions||[]).map(x=>`<div class="row"><span>${esc(x.mode)} · ${x.score_percent==null?'—':esc(x.score_percent)+'%'}</span><b>${x.passed?'PASS':'REVIEW'}</b></div>`).join('')||'<p>No state practice exam attempts yet.</p>'}</div>`;
 const host=document.querySelector('#agentPortal .portal-content,#agentPortal .content,#agentPortal')||document.body;if(!document.getElementById('launchAcademyPanel')){const d=document.createElement('section');d.id='launchAcademyPanel';d.innerHTML=html;host.appendChild(d)}else document.getElementById('launchAcademyPanel').innerHTML=html;
 }
 window.allshieldRefreshLaunchAcademy=render;setTimeout(render,1600);
})();