(() => {
 const sb=window.allshieldSupabase;if(!sb)return;let support=null;
 const ownerOnly=()=>{if(window.currentAllshieldProfile?.role!=='owner')throw new Error('Owner access required.')};
 const nameOf=p=>((p.first_name||'')+' '+(p.last_name||'')).trim()||p.username||'Agent';
 async function profile(id){const {data,error}=await sb.from('profiles').select('id,username,email,first_name,last_name,role,status,resident_state').eq('id',id).single();if(error)throw error;if(!['agent','team_lead','manager'].includes(data.role))throw new Error('View As is for field-agent profiles.');return data}
 function banner(){let b=document.getElementById('ownerSupportBanner');if(b)return b;b=document.createElement('div');b.id='ownerSupportBanner';b.innerHTML='<div><strong id="ownerSupportName">OWNER SUPPORT MODE</strong><span>You remain signed in as Owner. Agent-context actions are audited.</span></div><button class="btn btn-primary" onclick="exitOwnerViewAs()">Exit View As</button>';document.body.appendChild(b);return b}
 async function begin(p){const u=(await sb.auth.getUser()).data.user;const {data,error}=await sb.from('owner_support_sessions').insert({owner_id:u.id,target_user_id:p.id,reason:'Owner View As support',metadata:{target_username:p.username,target_role:p.role}}).select('id').single();if(error)throw error;return data.id}
 async function end(){if(support?.sessionId)await sb.from('owner_support_sessions').update({ended_at:new Date().toISOString()}).eq('id',support.sessionId)}
 function setContext(p,sessionId){window.allshieldSupportContext={active:true,ownerProfile:window.currentAllshieldProfile,targetProfile:p,targetUserId:p.id,targetUsername:p.username,sessionId};window.currentAllshieldSupportProfile=p;document.body.classList.add('owner-view-as-active')}
 function clear(){delete window.allshieldSupportContext;delete window.currentAllshieldSupportProfile;document.body.classList.remove('owner-view-as-active')}
 window.allshieldEffectiveUserId=async()=>{if(window.allshieldSupportContext?.active)return window.allshieldSupportContext.targetUserId;const {data,error}=await sb.auth.getUser();if(error)throw error;return data.user?.id};
 window.allshieldEffectiveProfile=()=>window.allshieldSupportContext?.active?window.allshieldSupportContext.targetProfile:window.currentAllshieldProfile;
 window.ownerViewAsAgent=async function(id,username='agent'){try{ownerOnly();if(support)await window.exitOwnerViewAs();const p=await profile(id),sessionId=await begin(p);support={profile:p,sessionId};setContext(p,sessionId);const b=banner();document.getElementById('ownerSupportName').textContent=`Viewing as ${nameOf(p)} (${p.username||username})`;b.classList.add('show');document.getElementById('ownerPortal')?.classList.remove('show');document.getElementById('adminPortal')?.classList.remove('show');document.getElementById('agentPortal')?.classList.add('show');const first=document.querySelector('#agentPortal .sidebar .side-link');if(first&&typeof window.showAgentView==='function')window.showAgentView('dashboard',first);window.scrollTo({top:0,behavior:'auto'});window.dispatchEvent(new CustomEvent('allshield:view-as-start',{detail:{target:p,sessionId}}));}catch(e){alert(e.message||e)}};
 window.exitOwnerViewAs=async function(){try{await end()}catch(e){console.error(e)}document.getElementById('ownerSupportBanner')?.classList.remove('show');document.getElementById('agentPortal')?.classList.remove('show');clear();support=null;document.getElementById('ownerPortal')?.classList.add('show');const first=document.querySelector('#ownerPortal .sidebar .side-link');if(first&&typeof window.showOwnerView==='function')window.showOwnerView('dashboard',first);window.scrollTo({top:0,behavior:'auto'});window.dispatchEvent(new Event('allshield:view-as-end'))};
 const oldReturn=window.returnHome;if(typeof oldReturn==='function')window.returnHome=function(){if(window.allshieldSupportContext?.active){window.exitOwnerViewAs();return}return oldReturn.apply(this,arguments)};
 const originalRefresh=window.refreshTeamAccounts;if(typeof originalRefresh==='function')window.refreshTeamAccounts=async function(){await originalRefresh();try{if(window.currentAllshieldProfile?.role!=='owner')return;const users=await window.allshieldListTeamUsers(),rows=[...document.querySelectorAll('#teamAccountRows tr[data-search]')];rows.forEach((row,i)=>{const u=users[i];if(!u||!['agent','team_lead','manager'].includes(u.role))return;const a=row.querySelector('.team-actions');if(!a||a.querySelector('[data-view-as]'))return;const b=document.createElement('button');b.className='tiny-btn';b.dataset.viewAs='1';b.textContent='View As';b.onclick=()=>window.ownerViewAsAgent(u.id,u.username||'agent');a.prepend(b)})}catch(e){console.error(e)}};
 const style=document.createElement('style');style.textContent=`#ownerSupportBanner{position:fixed;left:0;right:0;top:0;z-index:100000;display:none;align-items:center;justify-content:space-between;gap:18px;padding:10px 22px;background:#6d3be7;color:white;box-shadow:0 8px 30px rgba(0,0,0,.35)}#ownerSupportBanner.show{display:flex}#ownerSupportBanner div{display:flex;gap:14px;align-items:center;flex-wrap:wrap}#ownerSupportBanner span{font-size:12px;opacity:.9}.owner-view-as-active #agentPortal{padding-top:58px}.owner-view-as-active #agentPortal .portal-top .left strong:after{content:' • OWNER SUPPORT MODE';color:#bda7ff}`;document.head.appendChild(style);
})();