import { readFile, readdir } from "node:fs/promises";
const required = ["index.html","styles.css","app.js","backend.js","config.js","team-accounts.js","view-registry-bridge.js","support-context.js","build-info.js","live-platform.js","ops-platform.js","recruiting-platform.js","crm-platform.js","owner-control-platform.js","comp-user-platform.js","delegation-platform.js","comp-calculation-ui.js","launch-academy.js","academy-exam-ui-v2.js","mail-connector-ui.js","finance-import-ui.js","owner-view-as.js","owner-testing-overview.js","social-live-ui.js","ai-live-ui.js","brand-normalizer.js","production-hardening.js","build-history-ui.js","production-health.js"];
for (const file of required) await readFile(file);
for (const file of required) {
  const text = await readFile(file, "utf8");
  if (/data:image\//i.test(text)) throw new Error(`Embedded image remains in browser source: ${file}`);
  if (/sb_secret_/i.test(text) || /SUPABASE_SERVICE_ROLE_KEY/i.test(text)) throw new Error(`Privileged Supabase credential marker found in browser source: ${file}`);
  if (/IONOS_EMAIL_PASSWORD/i.test(text)) throw new Error(`IONOS mailbox secret reference found in browser source: ${file}`);
}
const html = await readFile("index.html", "utf8");
for (const ref of ["./styles.css","./app.js","./backend.js","./config.js","./team-accounts.js"]) if (!html.includes(ref)) throw new Error(`Missing HTML reference: ${ref}`);
if (!html.includes("Team Accounts")) throw new Error("Owner Team Accounts navigation is missing.");
const config = await readFile("config.js", "utf8");
for (const ref of ["view-registry-bridge.js","support-context.js","build-info.js","launch-academy.js","academy-exam-ui-v2.js","mail-connector-ui.js","finance-import-ui.js","owner-view-as.js","owner-testing-overview.js","social-live-ui.js","ai-live-ui.js","brand-normalizer.js","production-hardening.js","build-history-ui.js","production-health.js"]) if (!config.includes(ref)) throw new Error(`Production module is not loaded: ${ref}`);
if (config.indexOf('view-registry-bridge.js') > config.indexOf('live-platform.js')) throw new Error('View registry bridge must load before production modules.');
if (config.indexOf('support-context.js') > config.indexOf('live-platform.js')) throw new Error('Support context must load before live portal modules.');
const bridge = await readFile("view-registry-bridge.js","utf8");
for (const marker of ["window.agentViews = agentViews","window.adminViews = adminViews","window.ownerViews = ownerViews","__allshieldViewRegistryReady"]) if(!bridge.includes(marker)) throw new Error(`View registry bridge marker missing: ${marker}`);
const viewAs = await readFile("owner-view-as.js","utf8");
for (const marker of ["owner_support_sessions","ownerSupportBanner","targetUserId","agentPortal","Exit View As"]) if(!viewAs.includes(marker)) throw new Error(`Full Owner View As marker missing: ${marker}`);
const support = await readFile("support-context.js","utf8");
if(!support.includes("allshieldEffectiveUserId") || !support.includes("targetUserId")) throw new Error("Owner support context routing is incomplete.");
const build = await readFile("build-info.js","utf8");
if(!build.includes("B2026.08.19.001") || !build.includes("allshieldBuildBadge")) throw new Error("Visible build identification is incomplete.");
const builds = await readFile("build-history-ui.js","utf8");
if(!builds.includes("build_history") || !builds.includes("Build History")) throw new Error("Owner build history UI is incomplete.");
const testing = await readFile("owner-testing-overview.js","utf8");
if (!testing.includes("Agent Testing & Scores") || !testing.includes("exam_attempts") || !testing.includes("ownerViewAsAgent")) throw new Error("Owner testing overview is incomplete.");
const social = await readFile("social-live-ui.js","utf8");
if (!social.includes("social_posts") || !social.includes("social_accounts") || !social.includes("queued")) throw new Error("Live social state handling is incomplete.");
const ai = await readFile("ai-live-ui.js","utf8");
if (!ai.includes("/functions/v1/ai-assistant") || !ai.includes("rewrite_social")) throw new Error("Live AI UI is not wired to the backend.");
const brand = await readFile("brand-normalizer.js","utf8");
if (!brand.includes("brand-914a23072410.webp") || !brand.includes("MutationObserver")) throw new Error("Approved-logo enforcement is incomplete.");
const hardening = await readFile("production-hardening.js","utf8");
for (const marker of ["app_settings","owner-vault","media_assets"]) if(!hardening.includes(marker)) throw new Error(`Production hardening marker missing: ${marker}`);
const health = await readFile("production-health.js","utf8");
for (const marker of ["GA / TX / FL / TN Academy","mail_sync_runs","ai-provider-status","Owner View As","Approved logo"]) if(!health.includes(marker)) throw new Error(`Production health marker missing: ${marker}`);
const assets = (await readdir("assets")).filter(name => name !== "manifest.json");
if (!assets.includes("brand-914a23072410.webp")) throw new Error("Approved logo asset is missing.");
console.log(`Static validation passed: ${assets.length} image assets, portal registry/support context/build tracking loaded, Owner testing/View As/social/AI/brand/system-health enforcement present, no embedded images or browser secrets.`);
