import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const money=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const monthBounds=(m:string)=>{const [y,mo]=m.split('-').map(Number);const start=`${m}-01`;const end=new Date(Date.UTC(y,mo,0)).toISOString().slice(0,10);return {start,end}};
const secondFriday=(m:string)=>{const [y,mo]=m.split('-').map(Number);const d=new Date(Date.UTC(y,mo,1));d.setUTCMonth(d.getUTCMonth()+1,1);let add=(5-d.getUTCDay()+7)%7;d.setUTCDate(1+add+7);return d.toISOString().slice(0,10)};
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
 const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Missing authorization'},401);const token=auth.slice(7);
 const url=Deno.env.get('SUPABASE_URL')!;const pub=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}').default||Deno.env.get('SUPABASE_ANON_KEY')!;const sec=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const uc=createClient(url,pub,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data:ud,error:ue}=await uc.auth.getUser(token);if(ue||!ud.user)return json({error:'Invalid session'},401);
 const admin=createClient(url,sec,{auth:{persistSession:false,autoRefreshToken:false}});const {data:actor}=await admin.from('profiles').select('id,role,status').eq('id',ud.user.id).single();if(!actor||actor.status!=='active')return json({error:'Active account required'},403);
 const {data:perms}=await admin.from('comp_permissions').select('permission_key').eq('user_id',actor.id);const keys=new Set((perms||[]).map((x:any)=>x.permission_key));const allowed=actor.role==='owner'||keys.has('payroll_manage')||keys.has('payroll_run');if(!allowed)return json({error:'Payroll permission required'},403);
 const body=await req.json();const action=String(body.action||'');const {data:campaign}=await admin.from('campaigns').select('*').eq('code',body.campaign_code||'ACA_DIALER').single();if(!campaign)return json({error:'Campaign not found'},404);
 const {data:plan}=await admin.from('comp_plan_versions').select('*').eq('campaign_id',campaign.id).eq('status','published').order('version',{ascending:false}).limit(1).maybeSingle();if(!plan)return json({error:'Publish a compensation plan before running calculations.'},409);
 const {data:rules}=await admin.from('comp_bonus_rules').select('*').eq('plan_version_id',plan.id);const highest=(type:string,units:number)=>((rules||[]).filter((r:any)=>r.rule_type===type&&units>=Number(r.threshold)).sort((a:any,b:any)=>Number(b.threshold)-Number(a.threshold))[0]||null);
 if(action==='calculate_month'){
  const month=String(body.month||'');if(!/^\d{4}-\d{2}$/.test(month))return json({error:'Month must be YYYY-MM'},400);const {start,end}=monthBounds(month);const {data:enrs}=await admin.from('campaign_enrollments').select('agent_id,qualified_at').eq('campaign_id',campaign.id).eq('status','qualified').eq('card_orderable',true).gte('qualified_at',start+'T00:00:00Z').lte('qualified_at',end+'T23:59:59Z');const counts=new Map<string,number>();for(const e of enrs||[])counts.set(e.agent_id,(counts.get(e.agent_id)||0)+1);
  const {data:rels}=await admin.from('leadership_relationships').select('leader_id,member_id,generation,active').eq('campaign_id',campaign.id).eq('active',true);const direct=(rels||[]).filter((r:any)=>r.generation===1);const payday=secondFriday(month);let created=0,total=0;
  const add=async(uid:string,type:string,amount:number,units:number,ref:string,meta:any={})=>{if(amount<=0)return;const row={user_id:uid,campaign_id:campaign.id,plan_version_id:plan.id,earning_type:type,source_period_start:start,source_period_end:end,units,rate:amount,amount,status:'pending',payable_on:payday,source_ref:ref,metadata:meta};const {error}=await admin.from('comp_ledger').upsert(row,{onConflict:'source_ref'});if(!error){created++;total+=amount}};
  for(const [uid,n] of counts){const r=highest('agent_monthly',n);if(r)await add(uid,'agent_monthly_bonus',Number(r.amount),n,`agentbonus:${campaign.id}:${month}:${uid}`,{threshold:r.threshold})}
  const leaders=new Set(direct.map((r:any)=>r.leader_id));for(const leader of leaders){const members=direct.filter((r:any)=>r.leader_id===leader).map((r:any)=>r.member_id);for(const member of members){const n=counts.get(member)||0;const r=highest('manager_direct_coaching',n);if(r)await add(leader,'manager_direct_coaching_bonus',Number(r.amount),n,`coach:${campaign.id}:${month}:${leader}:${member}`,{member_id:member,threshold:r.threshold})}
    const market=(counts.get(leader)||0)+members.reduce((s:number,m:string)=>s+(counts.get(m)||0),0);const mr=highest('market_monthly',market);if(mr)await add(leader,'market_monthly_bonus',Number(mr.amount),market,`market:${campaign.id}:${month}:${leader}`,{threshold:mr.threshold,scope:'self_plus_first_generation'});
    for(const promoted of members){const promotedMembers=direct.filter((r:any)=>r.leader_id===promoted).map((r:any)=>r.member_id);if(!promotedMembers.length)continue;const promotedMarket=(counts.get(promoted)||0)+promotedMembers.reduce((s:number,m:string)=>s+(counts.get(m)||0),0);const pr=highest('promoting_manager_market',promotedMarket);if(pr)await add(leader,'promoting_manager_market_bonus',Number(pr.amount),promotedMarket,`promotermarket:${campaign.id}:${month}:${leader}:${promoted}`,{promoted_manager_id:promoted,threshold:pr.threshold})}
  }
  const users=new Set<string>([...counts.keys(),...direct.map((r:any)=>r.leader_id),...direct.map((r:any)=>r.member_id)]);const promo=plan.config?.promotion_rule||{};for(const uid of users){const members=direct.filter((r:any)=>r.leader_id===uid).map((r:any)=>r.member_id);const directCount=members.length;const fg=members.reduce((s:number,m:string)=>s+(counts.get(m)||0),0);const personal=counts.get(uid)||0;const {data:old}=await admin.from('promotion_qualification_snapshots').select('compliance_passed,sop_passed').eq('campaign_id',campaign.id).eq('user_id',uid).eq('qualification_month',start).maybeSingle();const compliance=old?.compliance_passed||false,sop=old?.sop_passed||false;const productionOk=(personal+fg)>=Number(promo.team_enrollments_required||500)&&directCount>=Number(promo.direct_agents_required||2);const qualifies=productionOk&&compliance&&sop;await admin.from('promotion_qualification_snapshots').upsert({campaign_id:campaign.id,user_id:uid,qualification_month:start,personal_enrollments:personal,first_generation_enrollments:fg,active_direct_agents:directCount,compliance_passed:compliance,sop_passed:sop,qualifies,metadata:{production_qualified:productionOk}},{onConflict:'campaign_id,user_id,qualification_month'})}
  return json({ok:true,month,qualified_enrollments:(enrs||[]).length,ledger_entries_processed:created,bonus_total:money(total),bonus_payable_on:payday});
 }
 if(action==='calculate_residuals'){
  const policyYear=Number(body.policy_year||1);if(policyYear<1)return json({error:'Invalid policy year'},400);const {data:splits}=await admin.from('comp_residual_splits').select('*').eq('plan_version_id',plan.id).eq('policy_year',policyYear);const agentRate=Number((splits||[]).find((s:any)=>s.beneficiary_role==='agent')?.amount_per_member||0),managerRate=Number((splits||[]).find((s:any)=>s.beneficiary_role==='manager')?.amount_per_member||0);const asOf=String(body.as_of||new Date().toISOString().slice(0,10));const {data:enrs}=await admin.from('campaign_enrollments').select('id,agent_id,coverage_effective_date').eq('campaign_id',campaign.id).eq('residual_eligible',true).eq('reconciliation_status','verified').lte('coverage_effective_date',asOf);const {data:rels}=await admin.from('leadership_relationships').select('leader_id,member_id,generation,active').eq('campaign_id',campaign.id).eq('active',true).eq('generation',1);const leaderByMember=new Map((rels||[]).map((r:any)=>[r.member_id,r.leader_id]));const agentCounts=new Map<string,number>(),managerCounts=new Map<string,number>();for(const e of enrs||[]){agentCounts.set(e.agent_id,(agentCounts.get(e.agent_id)||0)+1);const leader=leaderByMember.get(e.agent_id);if(leader)managerCounts.set(leader,(managerCounts.get(leader)||0)+1)}let total=0,entries=0;for(const [uid,n] of agentCounts){const amount=money(n*agentRate);if(amount<=0)continue;await admin.from('comp_ledger').upsert({user_id:uid,campaign_id:campaign.id,plan_version_id:plan.id,earning_type:'residual_agent',source_period_start:asOf,source_period_end:asOf,units:n,rate:agentRate,amount,status:'pending',payable_on:asOf,source_ref:`residual:agent:${campaign.id}:py${policyYear}:${asOf}:${uid}`,metadata:{policy_year:policyYear}},{onConflict:'source_ref'});total+=amount;entries++}for(const [uid,n] of managerCounts){const amount=money(n*managerRate);if(amount<=0)continue;await admin.from('comp_ledger').upsert({user_id:uid,campaign_id:campaign.id,plan_version_id:plan.id,earning_type:'residual_manager',source_period_start:asOf,source_period_end:asOf,units:n,rate:managerRate,amount,status:'pending',payable_on:asOf,source_ref:`residual:manager:${campaign.id}:py${policyYear}:${asOf}:${uid}`,metadata:{policy_year:policyYear}},{onConflict:'source_ref'});total+=amount;entries++}return json({ok:true,policy_year:policyYear,eligible_members:(enrs||[]).length,entries,total:money(total),agent_rate:agentRate,manager_rate:managerRate});
 }
 return json({error:'Unknown action'},400);
}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});