import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const money=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const nextFriday=(d:Date)=>{const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));let add=(5-x.getUTCDay()+7)%7;if(add===0)add=7;x.setUTCDate(x.getUTCDate()+add);return x.toISOString().slice(0,10)};
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
try{
 const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"Missing authorization"},401);const token=auth.slice(7);
 const url=Deno.env.get("SUPABASE_URL")!;const pub=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default||Deno.env.get("SUPABASE_ANON_KEY")!;const sec=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
 const uc=createClient(url,pub,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data:ud,error:ue}=await uc.auth.getUser(token);if(ue||!ud.user)return json({error:"Invalid session"},401);
 const admin=createClient(url,sec,{auth:{persistSession:false,autoRefreshToken:false}});const {data:actor}=await admin.from("profiles").select("id,role,status").eq("id",ud.user.id).single();if(!actor||actor.status!=="active")return json({error:"Active account required"},403);
 const {data:perms}=await admin.from("comp_permissions").select("permission_key").eq("user_id",actor.id);const pset=new Set((perms||[]).map((x:any)=>x.permission_key));const owner=actor.role==="owner";const canComp=owner||pset.has("comp_manage")||pset.has("comp_edit");const canPayroll=owner||pset.has("payroll_manage")||pset.has("payroll_run");
 const body=await req.json();const action=String(body.action||"");
 const {data:campaign}=await admin.from("campaigns").select("*").eq("code",body.campaign_code||"ACA_DIALER").single();if(!campaign)return json({error:"Campaign not found"},404);
 if(action==="get_dashboard"){
   if(!(canComp||canPayroll))return json({error:"Compensation access required"},403);
   const {data:plans}=await admin.from("comp_plan_versions").select("*").eq("campaign_id",campaign.id).order("version",{ascending:false});const plan=plans?.[0]||null;
   const [rules,residuals,contracts,runs,ledger]=await Promise.all([
    plan?admin.from("comp_bonus_rules").select("*").eq("plan_version_id",plan.id).order("rule_type").order("threshold"):Promise.resolve({data:[]}),
    plan?admin.from("comp_residual_splits").select("*").eq("plan_version_id",plan.id).order("policy_year"):Promise.resolve({data:[]}),
    admin.from("contract_plan_versions").select("id,version,status,title,effective_from,effective_to,published_at").eq("campaign_id",campaign.id).order("version",{ascending:false}).limit(5),
    admin.from("payroll_runs").select("*").eq("campaign_id",campaign.id).order("period_end",{ascending:false}).limit(10),
    admin.from("comp_ledger").select("status,amount").eq("campaign_id",campaign.id)
   ] as any);
   const totals:any={earned:0,pending:0,paid:0};for(const x of ledger.data||[]){totals[x.status]=(totals[x.status]||0)+Number(x.amount||0)};
   return json({campaign,plan,rules:rules.data||[],residuals:residuals.data||[],contracts:contracts.data||[],payroll_runs:runs.data||[],ledger_totals:totals,permissions:[...pset],owner});
 }
 if(action==="update_draft"){
   if(!canComp)return json({error:"Compensation edit permission required"},403);const planId=String(body.plan_id||"");const {data:plan}=await admin.from("comp_plan_versions").select("*").eq("id",planId).single();if(!plan||plan.campaign_id!==campaign.id)return json({error:"Plan not found"},404);if(plan.status!=="draft")return json({error:"Only draft versions can be edited. Create a new version before changing a published plan."},409);
   const before=plan;const patch:any={};for(const k of ["effective_from","effective_to","base_enrollment_amount","weekly_arrears_days","payday_dow","open_enrollment_start_mmdd","open_enrollment_end_mmdd","reconciliation_end_mmdd","residual_pool_per_member","config","contract_terms"])if(body[k]!==undefined)patch[k]=body[k];
   const {data:updated,error}=await admin.from("comp_plan_versions").update(patch).eq("id",planId).select().single();if(error)return json({error:error.message},400);
   if(Array.isArray(body.bonus_rules)){await admin.from("comp_bonus_rules").delete().eq("plan_version_id",planId);if(body.bonus_rules.length){const rows=body.bonus_rules.map((r:any)=>({plan_version_id:planId,rule_type:r.rule_type,threshold:r.threshold,amount:r.amount,generation_scope:r.generation_scope||null,metadata:r.metadata||{}}));const {error:e}=await admin.from("comp_bonus_rules").insert(rows);if(e)return json({error:e.message},400)}}
   if(Array.isArray(body.residual_splits)){await admin.from("comp_residual_splits").delete().eq("plan_version_id",planId);if(body.residual_splits.length){const rows=body.residual_splits.map((r:any)=>({plan_version_id:planId,policy_year:r.policy_year,beneficiary_role:r.beneficiary_role,amount_per_member:r.amount_per_member}));const {error:e}=await admin.from("comp_residual_splits").insert(rows);if(e)return json({error:e.message},400)}}
   await admin.from("comp_plan_change_log").insert({plan_version_id:planId,actor_id:actor.id,action:"draft_updated",before_state:before,after_state:updated});return json({ok:true,plan:updated});
 }
 if(action==="create_draft"){
   if(!canComp)return json({error:"Compensation edit permission required"},403);const {data:last}=await admin.from("comp_plan_versions").select("*").eq("campaign_id",campaign.id).order("version",{ascending:false}).limit(1).single();if(!last)return json({error:"No source plan"},404);
   const {data:newp,error}=await admin.from("comp_plan_versions").insert({campaign_id:campaign.id,version:last.version+1,status:"draft",effective_from:body.effective_from||last.effective_from,base_enrollment_amount:last.base_enrollment_amount,weekly_arrears_days:last.weekly_arrears_days,payday_dow:last.payday_dow,open_enrollment_start_mmdd:last.open_enrollment_start_mmdd,open_enrollment_end_mmdd:last.open_enrollment_end_mmdd,reconciliation_end_mmdd:last.reconciliation_end_mmdd,residual_pool_per_member:last.residual_pool_per_member,config:last.config,contract_terms:last.contract_terms,created_by:actor.id}).select().single();if(error)return json({error:error.message},400);
   const [{data:rules},{data:splits}]=await Promise.all([admin.from("comp_bonus_rules").select("rule_type,threshold,amount,generation_scope,metadata").eq("plan_version_id",last.id),admin.from("comp_residual_splits").select("policy_year,beneficiary_role,amount_per_member").eq("plan_version_id",last.id)]);if(rules?.length)await admin.from("comp_bonus_rules").insert(rules.map((r:any)=>({...r,plan_version_id:newp.id})));if(splits?.length)await admin.from("comp_residual_splits").insert(splits.map((r:any)=>({...r,plan_version_id:newp.id})));await admin.from("comp_plan_change_log").insert({plan_version_id:newp.id,actor_id:actor.id,action:"draft_created",after_state:newp});return json({ok:true,plan:newp});
 }
 if(action==="publish"){
   if(!canComp)return json({error:"Compensation publish permission required"},403);const planId=String(body.plan_id||"");const {data:plan}=await admin.from("comp_plan_versions").select("*").eq("id",planId).single();if(!plan||plan.status!=="draft")return json({error:"Draft plan required"},409);
   const [{data:rules},{data:splits}]=await Promise.all([admin.from("comp_bonus_rules").select("*").eq("plan_version_id",planId),admin.from("comp_residual_splits").select("*").eq("plan_version_id",planId)]);
   const prior=await admin.from("comp_plan_versions").select("id,effective_from").eq("campaign_id",campaign.id).eq("status","published");for(const p of prior.data||[]){const end=new Date(plan.effective_from+"T00:00:00Z");end.setUTCDate(end.getUTCDate()-1);await admin.from("comp_plan_versions").update({status:"superseded",effective_to:end.toISOString().slice(0,10)}).eq("id",p.id)}
   const {data:pubPlan,error}=await admin.from("comp_plan_versions").update({status:"published",published_by:actor.id,published_at:new Date().toISOString()}).eq("id",planId).select().single();if(error)return json({error:error.message},400);
   const agentRules=(rules||[]).filter((r:any)=>r.rule_type==="agent_monthly").sort((a:any,b:any)=>Number(a.threshold)-Number(b.threshold));const marketRules=(rules||[]).filter((r:any)=>r.rule_type==="market_monthly").sort((a:any,b:any)=>Number(a.threshold)-Number(b.threshold));
   const bodyText=`# ${campaign.name} Compensation Addendum — Version ${plan.version}\n\nEffective ${plan.effective_from}.\n\n## Qualified Enrollment Compensation\nA qualified enrollment is a carrier-approved enrollment that is card-orderable under the campaign. The licensed producer earns $${Number(plan.base_enrollment_amount).toFixed(2)} per qualified enrollment. Qualified enrollment compensation is not charged back to the agent under this campaign.\n\n## Payment Schedule\nPayments are issued weekly on Friday, ${plan.weekly_arrears_days} days in arrears.\n\n## Individual Monthly Bonuses\n${agentRules.map((r:any)=>`- ${r.threshold}+ qualified enrollments: $${Number(r.amount).toFixed(2)} bonus`).join("\n")}\nBonuses are scheduled for the second Friday of the following month.\n\n## Market Leadership Bonuses\n${marketRules.map((r:any)=>`- ${r.threshold}+ self plus first-generation enrollments: $${Number(r.amount).toFixed(2)} market bonus`).join("\n")}\n\n## Open Enrollment and Reconciliation\nStandard configured open-enrollment window: ${plan.open_enrollment_start_mmdd} through ${plan.open_enrollment_end_mmdd}; reconciliation through ${plan.reconciliation_end_mmdd}. Dates are campaign-version controlled and may change prospectively.\n\n## Residuals\nCurrent residual pool: $${Number(plan.residual_pool_per_member).toFixed(4)} per eligible member. ${splits?.map((s:any)=>`Policy year ${s.policy_year} ${s.beneficiary_role}: $${Number(s.amount_per_member).toFixed(4)}`).join("; ")}. Residual eligibility is determined after reconciliation.\n\n## Version Control\nThis addendum is tied to compensation plan version ${plan.version}. Future changes apply only from their stated effective date and do not retroactively rewrite earnings already accrued under prior versions.`;
   await admin.from("contract_plan_versions").upsert({campaign_id:campaign.id,comp_plan_version_id:planId,version:plan.version,status:"published",title:`${campaign.name} Compensation Addendum v${plan.version}`,body_markdown:bodyText,effective_from:plan.effective_from,effective_to:plan.effective_to,published_by:actor.id,published_at:new Date().toISOString(),created_by:actor.id},{onConflict:"campaign_id,version"});await admin.from("comp_plan_change_log").insert({plan_version_id:planId,actor_id:actor.id,action:"published",after_state:pubPlan});return json({ok:true,plan:pubPlan,contract_body:bodyText});
 }
 if(action==="grant_permission"||action==="revoke_permission"){
   if(!owner)return json({error:"Only Owner can delegate compensation authority"},403);const userId=String(body.user_id||"");const key=String(body.permission_key||"");const allowed=["comp_manage","comp_edit","payroll_manage","payroll_run"];if(!allowed.includes(key))return json({error:"Invalid permission"},400);if(action==="grant_permission"){await admin.from("comp_permissions").upsert({user_id:userId,permission_key:key,granted_by:actor.id},{onConflict:"user_id,permission_key"});}else{await admin.from("comp_permissions").delete().eq("user_id",userId).eq("permission_key",key)}return json({ok:true});
 }
 if(action==="calculate_period"){
   if(!canPayroll)return json({error:"Payroll permission required"},403);const start=String(body.period_start||"");const end=String(body.period_end||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))return json({error:"Valid period required"},400);
   const {data:plan}=await admin.from("comp_plan_versions").select("*").eq("campaign_id",campaign.id).eq("status","published").lte("effective_from",end).or(`effective_to.is.null,effective_to.gte.${start}`).order("version",{ascending:false}).limit(1).single();if(!plan)return json({error:"No published comp plan covers this period"},409);
   const {data:enrs}=await admin.from("campaign_enrollments").select("id,agent_id,qualified_at").eq("campaign_id",campaign.id).eq("status","qualified").eq("card_orderable",true).gte("qualified_at",start+"T00:00:00Z").lte("qualified_at",end+"T23:59:59Z");const by=new Map<string,number>();for(const e of enrs||[])by.set(e.agent_id,(by.get(e.agent_id)||0)+1);
   const payable=nextFriday(new Date(new Date(end+"T00:00:00Z").getTime()+Number(plan.weekly_arrears_days||14)*86400000));let total=0;for(const [uid,count] of by){const amount=money(count*Number(plan.base_enrollment_amount));total+=amount;const ref=`base:${campaign.id}:${start}:${end}:${uid}`;await admin.from("comp_ledger").upsert({user_id:uid,campaign_id:campaign.id,plan_version_id:plan.id,earning_type:"qualified_enrollment",source_period_start:start,source_period_end:end,units:count,rate:plan.base_enrollment_amount,amount,status:"pending",payable_on:payable,source_ref:ref,metadata:{qualified_definition:"carrier_approved_card_orderable"}},{onConflict:"source_ref"})}
   const {data:run}=await admin.from("payroll_runs").upsert({campaign_id:campaign.id,period_start:start,period_end:end,payable_on:payable,status:"calculated",gross_amount:money(total),created_by:actor.id},{onConflict:"campaign_id,period_start,period_end"}).select().single();return json({ok:true,qualified_enrollments:(enrs||[]).length,people:by.size,gross_amount:money(total),payable_on:payable,payroll_run:run});
 }
 return json({error:"Unknown action"},400);
}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});