import { createClient } from "npm:@supabase/supabase-js@2.112.3";
const BUILD="B2026.08.29.042";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const okError=(message:string,extra:any={})=>json({ok:false,error:message,...extra},200);
const now=()=>new Date().toISOString();
const clean=(v:any,n=30000)=>String(v??"").trim().slice(0,n);
const arr=(v:any)=>Array.isArray(v)?v:[];
const extract=(p:any)=>{if(typeof p?.output_text==='string')return p.output_text;const x:string[]=[];for(const i of p?.output||[])for(const c of i?.content||[])if(typeof c?.text==='string')x.push(c.text);return x.join('\n')};
const parse=(t:string)=>JSON.parse(t.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim());
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{
  const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Missing authorization'},401);
  const token=auth.slice(7),url=Deno.env.get('SUPABASE_URL')!,pub=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}').default||Deno.env.get('SUPABASE_ANON_KEY')!,sec=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const uc=createClient(url,pub,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const u=await uc.auth.getUser(token);if(u.error||!u.data.user)return json({error:'Invalid session'},401);
  const admin=createClient(url,sec,{auth:{persistSession:false,autoRefreshToken:false}});const pr=await admin.from('profiles').select('id,role,status').eq('id',u.data.user.id).single();if(pr.error||!pr.data||pr.data.status!=='active'||!['owner','admin'].includes(pr.data.role))return json({error:'Owner or Admin access required'},403);
  const actor=pr.data,b=await req.json(),action=String(b.action||'status');const openai=Deno.env.get('OPENAI_API_KEY')||'';const gateway=Deno.env.get('ALLSHIELD_VIDEO_PROVIDER_URL')||Deno.env.get('VICTOR_VIDEO_PROVIDER_URL')||Deno.env.get('MAYA_VIDEO_PROVIDER_URL')||'';const gatewaySecret=Deno.env.get('ALLSHIELD_VIDEO_PROVIDER_SECRET')||Deno.env.get('VICTOR_VIDEO_PROVIDER_SECRET')||Deno.env.get('MAYA_VIDEO_PROVIDER_SECRET')||'';
  const getProject=async(id:string)=>{const q=await admin.from('video_projects').select('*').eq('id',id).single();if(q.error)throw q.error;return q.data};
  if(action==='status')return json({ok:true,build:BUILD,backend_version:4,ai_ready:Boolean(openai),text_model:'gpt-5.6-sol',image_model:'gpt-image-2',voice_model:'gpt-4o-mini-tts',video_provider:'provider_gateway',video_provider_ready:Boolean(gateway&&gatewaySecret),legacy_sora_api_used:false,direct_video_api:false});
  if(action==='generate_package'||action==='generate_metadata'){
   const p=await getProject(String(b.project_id||''));if(!openai){if(clean(p.script)&&arr(p.storyboard).length)return json({ok:true,project:p,reused_existing_package:true,provider_ready:false});return okError('Professional creative provider is not configured. Add OPENAI_API_KEY to create new package content.',{setup_required:true,required_secret:'OPENAI_API_KEY',project:p})}
   if(!clean(p.source_material))return okError('Approved source material is required before generating new video copy.',{blocked:true,reason:'approved_source_material_required'});
   const prompt=`Return valid JSON only. Use ONLY supplied source material; never invent claims, figures, guarantees, carrier relationships, testimonials or legal promises. Project: ${p.title}. Type: ${p.project_type}. Audience: ${p.audience||''}. Objective: ${p.objective||''}. Tone: ${p.tone||''}. CTA: ${p.call_to_action||''}. SOURCE: ${clean(p.source_material,12000)}. JSON: {"hook":"","outline":[],"script":"","storyboard":[],"youtube_title":"","youtube_description":"","tags":[],"thumbnail_prompt":"","captions":"","clip_ideas":[]}`;
   const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${openai}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-sol',store:false,input:prompt})});const out=await r.json();if(!r.ok)return okError(out?.error?.message||`Provider error ${r.status}`);let x:any;try{x=parse(extract(out))}catch{return okError('Provider returned invalid JSON')};const patch={hook:clean(x.hook,600),outline:arr(x.outline),script:clean(x.script),storyboard:arr(x.storyboard),youtube_title:clean(x.youtube_title||p.title,100),youtube_description:clean(x.youtube_description,5000),tags:arr(x.tags).map(String).slice(0,30),thumbnail_prompt:clean(x.thumbnail_prompt,2000),captions:clean(x.captions),status:'script_ready',metadata:{...(p.metadata||{}),clip_ideas:arr(x.clip_ideas),package_engine:'openai:gpt-5.6-sol',provider_generation_status:'ready',provider_ready:true,package_generated_at:now()},updated_at:now()};const q=await admin.from('video_projects').update(patch).eq('id',p.id).select('*').single();if(q.error)throw q.error;return json({ok:true,project:q.data,engine:'openai:gpt-5.6-sol'});
  }
  if(action==='generate_thumbnail'){
   const p=await getProject(String(b.project_id||''));if(!openai)return okError('Professional image provider is not configured.',{setup_required:true,required_secret:'OPENAI_API_KEY'});const prompt=clean(b.prompt||p.thumbnail_prompt||`Professional thumbnail for ${p.title}`,3000);const r=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${openai}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-image-2',prompt:`ALLSHIELD professional video thumbnail. ${prompt}. No unsupported claims or other-company logos.`,size:p.project_type==='shorts'?'1024x1536':'1536x1024',quality:'medium',output_format:'png'})});const out=await r.json();if(!r.ok)return okError(out?.error?.message||`Image provider error ${r.status}`);const b64=out?.data?.[0]?.b64_json;if(!b64)return okError('No image returned');const raw=atob(b64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const path=`video-thumbnails/${p.id}/${crypto.randomUUID()}.png`;const up=await admin.storage.from('social-media').upload(path,bytes,{contentType:'image/png',upsert:false});if(up.error)throw up.error;const publicUrl=admin.storage.from('social-media').getPublicUrl(path).data.publicUrl;const a=await admin.from('video_project_assets').insert({project_id:p.id,created_by:actor.id,asset_type:'thumbnail',title:`Thumbnail — ${p.title}`,status:'ready',storage_bucket:'social-media',storage_path:path,public_url:publicUrl,orientation:p.project_type==='shorts'?'9:16':'16:9',metadata:{prompt,engine:'openai:gpt-image-2',approval_required:true}}).select('*').single();if(a.error)throw a.error;return json({ok:true,asset:a.data,media_url:publicUrl,approval_required:true});
  }
  if(action==='generate_voiceover'){
   const p=await getProject(String(b.project_id||''));if(!openai)return okError('Professional voice provider is not configured.',{setup_required:true,required_secret:'OPENAI_API_KEY'});const text=clean(b.text,4000);if(!text)return okError('Voiceover text is required');const voice=clean(b.voice||'cedar',40);const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{Authorization:`Bearer ${openai}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4o-mini-tts',voice,input:text,instructions:'Professional, warm, natural business narration. Avoid an exaggerated announcer voice.'})});if(!r.ok)return okError(`Voice provider error ${r.status}`);const bytes=new Uint8Array(await r.arrayBuffer());const path=`video-projects/${p.id}/voice/${crypto.randomUUID()}.mp3`;const up=await admin.storage.from('allshield-private').upload(path,bytes,{contentType:'audio/mpeg',upsert:false});if(up.error)throw up.error;const a=await admin.from('video_project_assets').insert({project_id:p.id,created_by:actor.id,asset_type:'voiceover',title:clean(b.title||'Voiceover',120),status:'ready',storage_bucket:'allshield-private',storage_path:path,scene_index:Number.isFinite(Number(b.scene_index))?Number(b.scene_index):null,metadata:{voice,engine:'openai:gpt-4o-mini-tts',approval_required:true}}).select('*').single();if(a.error)throw a.error;return json({ok:true,asset:a.data,approval_required:true});
  }
  if(action==='generate_scene_clip'){
   const p=await getProject(String(b.project_id||''));if(!gateway||!gatewaySecret)return okError('Durable video provider gateway is not configured.',{blocked:true,required:['ALLSHIELD_VIDEO_PROVIDER_URL','ALLSHIELD_VIDEO_PROVIDER_SECRET']});const idx=Number(b.scene_index||0),scene=arr(p.storyboard)[idx]||{};const prompt=clean(b.prompt||scene.visual_direction||scene.sora_prompt,4000);if(!prompt)return okError('Scene visual prompt is required');const r=await fetch(gateway,{method:'POST',headers:{Authorization:`Bearer ${gatewaySecret}`,'Content-Type':'application/json'},body:JSON.stringify({action:'create_scene_draft',project_id:p.id,scene_index:idx,prompt,orientation:p.orientation||'16:9',approval_required:true,publish_allowed:false})});const out=await r.json().catch(()=>({}));if(!r.ok)return okError(out?.error||`Video provider error ${r.status}`);const a=await admin.from('video_project_assets').insert({project_id:p.id,created_by:actor.id,asset_type:'ai_clip',title:clean(b.title||scene.title||`Scene ${idx+1}`,160),status:'generating',orientation:p.orientation,scene_index:idx,metadata:{provider_job:out,engine:'provider_gateway',prompt,approval_required:true,publish_allowed:false}}).select('*').single();if(a.error)throw a.error;return json({ok:true,asset:a.data,job:out,approval_required:true,publish_allowed:false});
  }
  if(action==='sync_clips')return okError('Provider-specific synchronization must be handled through the configured durable video gateway adapter.',{blocked:!gateway});
  return okError('Unknown action');
 }catch(e){return json({error:e instanceof Error?e.message:String(e),build:BUILD},500)}
});
