from pathlib import Path


def rep(text, old, new, label):
    if old not in text:
        raise SystemExit(f'missing patch target: {label}')
    return text.replace(old, new, 1)

p=Path('supabase/functions/social-connection-admin/index.ts')
s=p.read_text()
s=rep(s,"const BUILD='B2026.08.29.045';","const BUILD='B2026.08.29.047';",'build')
old="tiktok:{label:'TikTok',platforms:['tiktok'],credential_names:['TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET'],fields:[['TIKTOK_CLIENT_KEY','TikTok Client Key','text'],['TIKTOK_CLIENT_SECRET','TikTok Client Secret','password']],oauth:true,guide:['Create/select the TikTok developer app.','Enable Login Kit and Content Posting API.','Request user.info.basic, video.publish and video.upload.','Add the callback URL shown here.','Save the Client Key and Client Secret here, then connect. TikTok may restrict unaudited Direct Post clients to private visibility until its audit is complete.']},"
new="tiktok:{label:'TikTok',platforms:['tiktok'],credential_names:['TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET'],fields:[['TIKTOK_CLIENT_KEY','TikTok Client Key','text'],['TIKTOK_CLIENT_SECRET','TikTok Client Secret','password']],oauth:true,links:[['Create ALLSHIELD TikTok Account','https://www.tiktok.com/signup'],['Open TikTok Developer Portal','https://developers.tiktok.com/']],guide:['Create the official ALLSHIELD TikTok account first if one does not exist.','Create a TikTok for Developers account using an ALLSHIELD business email and create an organization named ALLSHIELD Insurance Group.','Register a Web app for https://allshieldinsurancegroup.com and add Login Kit, TikTok API/Display API, and Content Posting API.','Use https://allshieldinsurancegroup.com/social-privacy.html as the Privacy Policy URL and https://allshieldinsurancegroup.com/social-terms.html as the Terms of Service URL, then verify the ALLSHIELD domain/URL properties in TikTok.','Add the callback URL shown here to Login Kit.','Request user.info.basic, user.info.stats, video.list, video.publish and video.upload.','Submit the app for TikTok review. After API approval, copy the Client Key and Client Secret here and click Connect TikTok.','Direct Post from unaudited clients is restricted to private viewing. When TikTok approves the Content Posting audit, record that approval here and run Verify again before Maya is allowed to treat TikTok as public-post ready.']},"
s=rep(s,old,new,'tiktok provider')
helper="""
async function providerApproval(provider:string){const r=await db.from('social_provider_approval_status').select('*').eq('provider',provider).maybeSingle();return r.data||{provider,app_review_status:'not_submitted',posting_audit_status:'not_submitted'}}
async function refreshTikTokTokenIfNeeded(t:any,c:any){
 if(!t?.refresh_token)return t;const exp=t.expires_at?new Date(t.expires_at).getTime():0;if(exp>Date.now()+15*60*1000)return t;
 const cr=await credsFor('tiktok');const key=cr.get('TIKTOK_CLIENT_KEY'),secret=cr.get('TIKTOK_CLIENT_SECRET');if(!key||!secret)return t;
 const rr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Cache-Control':'no-cache'},body:new URLSearchParams({client_key:key,client_secret:secret,grant_type:'refresh_token',refresh_token:t.refresh_token})});
 const rt=await rr.json();if(!rr.ok||rt.error)return t;await storeToken('tiktok',c.connected_by,rt,c.external_account_id,{...(t.metadata||{}),provider:'tiktok',refreshed_at:now()});await setConn('tiktok',{token_expires_at:rt.expires_in?new Date(Date.now()+Number(rt.expires_in)*1000).toISOString():null,scopes:csv(rt.scope),error_message:null});return (await tokenFor('tiktok',c))||t
}
"""
anchor="async function capability(platform:string)"
if anchor not in s: raise SystemExit('missing capability anchor')
s=s.replace(anchor,helper+'\n'+anchor,1)
s=rep(s," const t=await tokenFor(platform,c);if(!t?.access_token){"," let t=await tokenFor(platform,c);if(platform==='tiktok'&&t)t=await refreshTikTokTokenIfNeeded(t,c);if(!t?.access_token){",'tiktok refresh hook')
old="else if(platform==='tiktok'){const r=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url',{headers:{Authorization:`Bearer ${t.access_token}`}});api=await r.json();const me=api?.data?.user||{};identity_ok=r.ok&&(!c.external_account_id||String(me.open_id||'')===String(c.external_account_id));if(granted.includes('video.publish')){const cr=await fetch('https://open.tiktokapis.com/v2/post/publish/creator_info/query/',{method:'POST',headers:{Authorization:`Bearer ${t.access_token}`,'Content-Type':'application/json; charset=UTF-8'}});extra.creator_info_status=cr.status;extra.creator_info_ok=cr.ok}}"
new="else if(platform==='tiktok'){const r=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url,follower_count,following_count,likes_count,video_count',{headers:{Authorization:`Bearer ${t.access_token}`}});api=await r.json();const me=api?.data?.user||{};identity_ok=r.ok&&(!c.external_account_id||String(me.open_id||'')===String(c.external_account_id));extra.stats_probe_ok=r.ok&&['follower_count','following_count','likes_count','video_count'].every(k=>typeof me[k]==='number');extra.account_stats={follower_count:me.follower_count??null,following_count:me.following_count??null,likes_count:me.likes_count??null,video_count:me.video_count??null};if(granted.includes('video.list')){const vr=await fetch('https://open.tiktokapis.com/v2/video/list/?fields=id,create_time,title,like_count,comment_count,share_count,view_count',{method:'POST',headers:{Authorization:`Bearer ${t.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({max_count:20})});const vj=await vr.json();const vids=vj?.data?.videos||[];extra.video_metrics_status=vr.status;extra.video_metrics_probe_ok=vr.ok&&(!vj?.error?.code||vj.error.code==='ok');extra.video_sample_count=vids.length;extra.recent_video_metrics=vids.reduce((a:any,v:any)=>({views:a.views+Number(v.view_count||0),likes:a.likes+Number(v.like_count||0),comments:a.comments+Number(v.comment_count||0),shares:a.shares+Number(v.share_count||0)}),{views:0,likes:0,comments:0,shares:0})}if(granted.includes('video.publish')){const cr=await fetch('https://open.tiktokapis.com/v2/post/publish/creator_info/query/',{method:'POST',headers:{Authorization:`Bearer ${t.access_token}`,'Content-Type':'application/json; charset=UTF-8'}});const cj=await cr.json();extra.creator_info_status=cr.status;extra.creator_info_ok=cr.ok;extra.privacy_level_options=cj?.data?.privacy_level_options||[]}const approval=await providerApproval('tiktok');extra.app_review_status=approval.app_review_status;extra.posting_audit_status=approval.posting_audit_status;extra.private_test_post_ready=extra.creator_info_ok===true;extra.public_post_ready=extra.creator_info_ok===true&&approval.posting_audit_status==='approved'}"
s=rep(s,old,new,'tiktok verification')
s=rep(s,"if(platform==='tiktok'&&cap.organic_publish_supported&&granted.includes('video.publish'))publish_ok=publish_ok&&extra.creator_info_ok===true;","if(platform==='tiktok'&&cap.organic_publish_supported&&granted.includes('video.publish'))publish_ok=publish_ok&&extra.creator_info_ok===true&&extra.posting_audit_status==='approved';",'tiktok public publish gate')
s=rep(s,"if(platform==='linkedin'&&cap.engagement_metrics_supported)engagement_ok=engagement_ok&&extra.engagement_probe_ok===true;","if(platform==='linkedin'&&cap.engagement_metrics_supported)engagement_ok=engagement_ok&&extra.engagement_probe_ok===true;if(platform==='tiktok'&&cap.engagement_metrics_supported)engagement_ok=engagement_ok&&extra.stats_probe_ok===true&&extra.video_metrics_probe_ok===true;",'tiktok engagement gate')
s=rep(s,"providers[k]={key:k,label:d.label,platforms:d.platforms,configured:d.credential_names.every((n:string)=>Boolean(m.get(n))),fields:d.fields,credential_names:d.credential_names,oauth_supported:Boolean(d.oauth),manual_setup:Boolean(d.manual),managed_via:d.managed_via||null,callback_url:callback(k),guide:d.guide}","providers[k]={key:k,label:d.label,platforms:d.platforms,configured:d.credential_names.every((n:string)=>Boolean(m.get(n))),fields:d.fields,credential_names:d.credential_names,oauth_supported:Boolean(d.oauth),manual_setup:Boolean(d.manual),managed_via:d.managed_via||null,callback_url:callback(k),guide:d.guide,links:d.links||[],approval:await providerApproval(k)}",'dashboard provider approval')
s=rep(s,"else if(provider==='tiktok'){const tr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:c.get('TIKTOK_CLIENT_KEY')!,client_secret:c.get('TIKTOK_CLIENT_SECRET')!,code,grant_type:'authorization_code',redirect_uri:redirect})});const t=await tr.json();if(!tr.ok||t.error)throw new Error(t?.error_description||t?.message||'TikTok token exchange failed');const ir=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url',{headers:{Authorization:`Bearer ${t.access_token}`}});const ij=await ir.json();const me=ij?.data?.user||{};await connected('tiktok',st.user_id,t,t.open_id||me.open_id||null,me.display_name||'TikTok',{provider:'tiktok',avatar_url:me.avatar_url||null})}","else if(provider==='tiktok'){const tr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:c.get('TIKTOK_CLIENT_KEY')!,client_secret:c.get('TIKTOK_CLIENT_SECRET')!,code,grant_type:'authorization_code',redirect_uri:redirect})});const t=await tr.json();if(!tr.ok||t.error)throw new Error(t?.error_description||t?.message||'TikTok token exchange failed');const ir=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url,follower_count,following_count,likes_count,video_count',{headers:{Authorization:`Bearer ${t.access_token}`}});const ij=await ir.json();const me=ij?.data?.user||{};await connected('tiktok',st.user_id,t,t.open_id||me.open_id||null,me.display_name||'TikTok',{provider:'tiktok',avatar_url:me.avatar_url||null,follower_count:me.follower_count??null,video_count:me.video_count??null})}",'tiktok callback')
s=rep(s,"if(p==='tiktok'){const scope='user.info.basic,video.publish,video.upload';","if(p==='tiktok'){const scope='user.info.basic,user.info.stats,video.list,video.publish,video.upload';",'tiktok scopes')
marker=" if(action==='guide'){"
insert=" if(action==='set_provider_approval_status'){const p=String(b.provider||'');if(p!=='tiktok')return json({error:'Approval tracking is not enabled for this provider'},400);const allowed=new Set(['not_submitted','submitted','approved','rejected','changes_requested']);const app=String(b.app_review_status||'not_submitted'),audit=String(b.posting_audit_status||'not_submitted');if(!allowed.has(app)||!allowed.has(audit))return json({error:'Invalid approval status'},400);const r=await db.from('social_provider_approval_status').upsert({provider:p,app_review_status:app,posting_audit_status:audit,notes:String(b.notes||'').slice(0,2000)||null,updated_by:a.id,updated_at:now()},{onConflict:'provider'}).select('*').single();if(r.error)throw r.error;return json({ok:true,approval:r.data,message:'TikTok review status saved. Run Verify again after any approval change.'})}\n"
if marker not in s: raise SystemExit('missing action insertion marker')
s=s.replace(marker,insert+marker,1)
p.write_text(s)

ui=Path('social-connection-center.js');u=ui.read_text()
u=rep(u,"const VERSION='B2026.08.29.045';","const VERSION='B2026.08.29.047';",'ui version')
old="const fields=(d.fields||[]).map(f=>`<div class=\"scc-field\"><label>${esc(f[1])}</label><input id=\"scc_${key}_${f[0]}\" class=\"mini-input\" type=\"${f[2]==='password'?'password':'text'}\" autocomplete=\"off\" placeholder=\"Paste ${esc(f[1])}\"></div>`).join('');return `<div class=\"scc-card\">"
new="const fields=(d.fields||[]).map(f=>`<div class=\"scc-field\"><label>${esc(f[1])}</label><input id=\"scc_${key}_${f[0]}\" class=\"mini-input\" type=\"${f[2]==='password'?'password':'text'}\" autocomplete=\"off\" placeholder=\"Paste ${esc(f[1])}\"></div>`).join('');const links=(d.links||[]).map(x=>`<a class=\"tiny-btn\" target=\"_blank\" rel=\"noopener\" href=\"${attr(x[1])}\">${esc(x[0])}</a>`).join('');const approval=key==='tiktok'?`<div class=\"scc-field\"><label>TikTok App Review</label><select id=\"sccTikTokAppReview\" class=\"mini-input\">${['not_submitted','submitted','approved','changes_requested','rejected'].map(x=>`<option value=\"${x}\" ${d.approval?.app_review_status===x?'selected':''}>${x.replaceAll('_',' ').toUpperCase()}</option>`).join('')}</select></div><div class=\"scc-field\"><label>TikTok Content Posting Audit</label><select id=\"sccTikTokPostingAudit\" class=\"mini-input\">${['not_submitted','submitted','approved','changes_requested','rejected'].map(x=>`<option value=\"${x}\" ${d.approval?.posting_audit_status===x?'selected':''}>${x.replaceAll('_',' ').toUpperCase()}</option>`).join('')}</select></div><div class=\"scc-actions\"><button class=\"tiny-btn\" onclick=\"allshieldSCCSaveTikTokApproval()\">Save TikTok Review Status</button></div><div class=\"scc-muted\">This records your external TikTok review result; ALLSHIELD still performs live API verification before marking the connection ready.</div>`:'';return `<div class=\"scc-card\">"
u=rep(u,old,new,'ui provider extras')
u=rep(u,"<div class=\"scc-actions\">${setup}${connect}${disconnect}<button class=\"tiny-btn\" onclick=\"allshieldSCCAssistant('${key}')\">What do I do next?</button></div><div id=\"sccDrawer_${key}\" class=\"scc-drawer\"><div class=\"kicker\">SECURE ONE-TIME SETUP</div>${fields}${fields?","<div class=\"scc-actions\">${links}${setup}${connect}${disconnect}<button class=\"tiny-btn\" onclick=\"allshieldSCCAssistant('${key}')\">What do I do next?</button></div><div id=\"sccDrawer_${key}\" class=\"scc-drawer\"><div class=\"kicker\">SECURE ONE-TIME SETUP</div>${fields}${approval}${fields?",'ui links and approval')
anchor="window.allshieldSCCSaveCredentials=async key=>"
i=u.find(anchor)
if i<0: raise SystemExit('missing save credentials anchor')
end=u.find(";\n",i)
if end<0: raise SystemExit('missing save credentials end')
end+=2
u=u[:end]+"window.allshieldSCCSaveTikTokApproval=async()=>{try{const app_review_status=document.getElementById('sccTikTokAppReview')?.value||'not_submitted',posting_audit_status=document.getElementById('sccTikTokPostingAudit')?.value||'not_submitted';const r=await edge({action:'set_provider_approval_status',provider:'tiktok',app_review_status,posting_audit_status});ASSIST=r.message||'TikTok review status saved.';await load()}catch(e){alert(e.message||e)}};\n"+u[end:]
# TikTok state detail block in platform card
old="const missing=(v.missing_scopes||[]).length?`<div class=\"scc-missing\">Missing permissions: ${esc(v.missing_scopes.join(', '))}</div>`:'';const checks="
new="const missing=(v.missing_scopes||[]).length?`<div class=\"scc-missing\">Missing permissions: ${esc(v.missing_scopes.join(', '))}</div>`:'';const tiktokState=p==='tiktok'?`<div class=\"scc-muted\" style=\"margin-top:8px\">Analytics: ${v.details?.stats_probe_ok&&v.details?.video_metrics_probe_ok?'READY':'PENDING'} • Private API test: ${v.details?.private_test_post_ready?'READY':'PENDING'} • Public posting audit: ${esc((v.details?.posting_audit_status||DASH?.providers?.tiktok?.approval?.posting_audit_status||'not_submitted').replaceAll('_',' ').toUpperCase())}</div>`:'';const checks="
u=rep(u,old,new,'tiktok status detail')
u=rep(u,"</div>${missing}${select}<div class=\"scc-actions\"><button class=\"tiny-btn\" onclick=\"allshieldSCCVerify('${p}')\">","</div>${missing}${tiktokState}${select}<div class=\"scc-actions\"><button class=\"tiny-btn\" onclick=\"allshieldSCCVerify('${p}')\">",'render tiktok status')
ui.write_text(u)

idx=Path('index.html');x=idx.read_text();x=x.replace('social-connection-center.js?v=B2026.08.29.045','social-connection-center.js?v=B2026.08.29.047');idx.write_text(x)
bi=Path('build-info.js');b=bi.read_text();b=b.replace("current_build:'B2026.08.29.045'","current_build:'B2026.08.29.047'").replace("label:'Production B045 — Professional Social Provider Verification — Certified'","label:'B047 Candidate — TikTok Professional Connection + Analytics'");bi.write_text(b)
