import { createClient } from "npm:@supabase/supabase-js@2.112.3";

const BUILD='B2026.08.29.048';
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const PUB=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}').default||Deno.env.get('SUPABASE_ANON_KEY')!;
const SECRET_KEYS=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');
const SEC=SECRET_KEYS.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SUPABASE_URL,SEC,{auth:{persistSession:false,autoRefreshToken:false}});
const fnBase=`${SUPABASE_URL}/functions/v1/social-connection-admin`;
const now=()=>new Date().toISOString();
const enc=(v:string)=>encodeURIComponent(v);
const csv=(v:any)=>Array.isArray(v)?v.map(String):String(v||'').split(/[ ,]+/).map(x=>x.trim()).filter(Boolean);
const uniq=(a:string[])=>[...new Set(a.filter(Boolean))];
const basic=(id:string,secret:string)=>`Basic ${btoa(`${id}:${secret}`)}`;
const allowedReturnHosts=new Set(['allshieldinsurancegroup.com','www.allshieldinsurancegroup.com','localhost','127.0.0.1']);
function safeReturn(v:string|null){try{const u=new URL(v||'');if((u.protocol==='http:'||u.protocol==='https:')&&allowedReturnHosts.has(u.hostname))return u.toString()}catch{}return 'https://allshieldinsurancegroup.com/'}
function b64url(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function pkce(){const bytes=crypto.getRandomValues(new Uint8Array(32));const verifier=b64url(bytes);const digest=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)));return {verifier,challenge:b64url(digest)}}

const PROVIDERS:any={
 meta:{label:'Facebook + Instagram',platforms:['facebook','instagram'],credential_names:['META_APP_ID','META_APP_SECRET'],fields:[['META_APP_ID','Meta App ID','text'],['META_APP_SECRET','Meta App Secret','password']],oauth:true,guide:['Create or select a Meta developer app for Allshield.','Add Facebook Login for Business / required Graph API products.','Add the callback URL shown here to the app OAuth redirect allowlist.','Request Page publishing/engagement and Instagram professional publishing/comment permissions.','Save the App ID and App Secret here, then click Connect Meta.']},
 tiktok:{label:'TikTok',platforms:['tiktok'],credential_names:['TIKTOK_CLIENT_KEY','TIKTOK_CLIENT_SECRET'],fields:[['TIKTOK_CLIENT_KEY','TikTok Client Key','text'],['TIKTOK_CLIENT_SECRET','TikTok Client Secret','password']],oauth:true,links:[['Create ALLSHIELD TikTok Account','https://www.tiktok.com/signup'],['Open TikTok Developer Portal','https://developers.tiktok.com/']],guide:['Create the official ALLSHIELD TikTok account first if one does not exist.','Create a TikTok for Developers account using an ALLSHIELD business email and create an organization named ALLSHIELD Insurance Group.','Register a Web app for https://allshieldinsurancegroup.com and add Login Kit, TikTok API/Display API, and Content Posting API.','Use https://allshieldinsurancegroup.com/social-privacy.html as the Privacy Policy URL and https://allshieldinsurancegroup.com/social-terms.html as the Terms of Service URL, then verify the ALLSHIELD domain/URL properties in TikTok.','Add the callback URL shown here to Login Kit.','Request user.info.basic, user.info.stats, video.list, video.publish and video.upload.','Submit the app for TikTok review. After API approval, copy the Client Key and Client Secret here and click Connect TikTok.','Direct Post from unaudited clients is restricted to private viewing. When TikTok approves the Content Posting audit, record that approval here and run Verify again before Maya is allowed to treat TikTok as public-post ready.']},
 linkedin:{label:'LinkedIn',platforms:['linkedin'],credential_names:['LINKEDIN_CLIENT_ID','LINKEDIN_CLIENT_SECRET'],fields:[['LINKEDIN_CLIENT_ID','LinkedIn Client ID','text'],['LINKEDIN_CLIENT_SECRET','LinkedIn Client Secret','password']],oauth:true,guide:['Create/select a LinkedIn developer app associated with the Allshield organization page.','Enable Sign In with LinkedIn using OpenID Connect and apply for Community Management API access.','Request r_organization_admin, r_organization_social, w_organization_social, r_organization_social_feed and w_organization_social_feed.','Add the callback URL shown here.','Save credentials and connect. Allshield must identify and verify the actual Company Page; a member-only login never counts as Maya-ready.']},
 youtube:{label:'YouTube',platforms:['youtube'],credential_names:['YOUTUBE_CLIENT_ID','YOUTUBE_CLIENT_SECRET'],fields:[['YOUTUBE_CLIENT_ID','Google OAuth Client ID','text'],['YOUTUBE_CLIENT_SECRET','Google OAuth Client Secret','password']],oauth:true,guide:['Create/select a Google Cloud OAuth web application.','Enable YouTube Data API v3 and YouTube Analytics API.','Add the callback URL shown here as an authorized redirect URI.','Configure the OAuth consent screen/verification and request youtube.upload, youtube.readonly, youtube.force-ssl and yt-analytics.readonly.','Save credentials and connect the official Allshield YouTube channel.']},
 x:{label:'X',platforms:['x'],credential_names:['X_CLIENT_ID','X_CLIENT_SECRET'],fields:[['X_CLIENT_ID','X Client ID','text'],['X_CLIENT_SECRET','X Client Secret','password']],oauth:true,guide:['Create/select an X developer application.','Enable OAuth 2.0 authorization code with PKCE.','Add this callback URL.','Grant tweet.read, users.read, tweet.write and offline.access.','Save credentials and connect.']},
 threads:{label:'Threads',platforms:['threads'],credential_names:['THREADS_APP_ID','THREADS_APP_SECRET'],fields:[['THREADS_APP_ID','Threads App ID','text'],['THREADS_APP_SECRET','Threads App Secret','password']],oauth:true,guide:['Create/select the Meta Threads app.','Configure Threads API and redirect URI.','Request Threads basic and content publishing permissions.','Save credentials and connect.','The current Allshield automation capability matrix will remain conservative until publishing/community functions are certified.']},
 pinterest:{label:'Pinterest',platforms:['pinterest'],credential_names:['PINTEREST_APP_ID','PINTEREST_APP_SECRET'],fields:[['PINTEREST_APP_ID','Pinterest App ID','text'],['PINTEREST_APP_SECRET','Pinterest App Secret','password']],oauth:true,guide:['Create/select a Pinterest developer app.','Add the callback URL.','Request account, pin and board permissions appropriate to the business account.','Save credentials and connect.','Allshield will verify identity even where full employee automation is not yet certified.']},
 reddit:{label:'Reddit',platforms:['reddit'],credential_names:['REDDIT_CLIENT_ID','REDDIT_CLIENT_SECRET'],fields:[['REDDIT_CLIENT_ID','Reddit Client ID','text'],['REDDIT_CLIENT_SECRET','Reddit Client Secret','password']],oauth:true,guide:['Create a Reddit web app.','Use this callback URL as the redirect URI.','Save Client ID and Client Secret.','Connect the authorized Allshield account.','Allshield will verify identity; autonomous publishing remains disabled until separately certified.']},
 snapchat:{label:'Snapchat',platforms:['snapchat'],credential_names:['SNAPCHAT_CLIENT_ID','SNAPCHAT_CLIENT_SECRET'],fields:[['SNAPCHAT_CLIENT_ID','Snapchat Client ID','text'],['SNAPCHAT_CLIENT_SECRET','Snapchat Client Secret','password']],oauth:false,manual:true,guide:['Snapchat requires provider-specific business/API approval before this connection can be automated.','You may securely save approved app credentials here, but Allshield will not claim an operational connection until a verified API workflow is implemented.']},
 whatsapp:{label:'WhatsApp Business',platforms:['whatsapp'],credential_names:['META_APP_ID','META_APP_SECRET'],fields:[],oauth:false,manual:true,managed_via:'Meta Business',guide:['WhatsApp Business is managed through Meta Business.','It is not treated as an organic social posting/comment channel in Maya’s current professional readiness gate.']},
 messenger:{label:'Messenger',platforms:['messenger'],credential_names:['META_APP_ID','META_APP_SECRET'],fields:[],oauth:false,manual:true,managed_via:'Meta Business',guide:['Messenger is managed through Meta Business/Page permissions.','It is not treated as a standalone organic social publishing channel in Maya’s current readiness gate.']}
};

function apiSecretMatches(req:Request){const key=String(req.headers.get('apikey')||'').trim();if(!key)return false;return Object.values(SECRET_KEYS).some(v=>typeof v==='string'&&v===key)||(typeof SEC==='string'&&SEC===key)}
async function actor(req:Request){if(apiSecretMatches(req)){const p=await db.from('profiles').select('id,role,status').in('role',['owner','admin']).eq('status','active').order('created_at',{ascending:true}).limit(1).maybeSingle();if(p.error||!p.data?.id)throw new Error('FORBIDDEN');return {...p.data,internal_service:true}}const h=req.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))throw new Error('AUTH');const token=h.slice(7);const uc=createClient(SUPABASE_URL,PUB,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const u=await uc.auth.getUser(token);if(u.error||!u.data.user)throw new Error('AUTH');const p=await db.from('profiles').select('id,role,status').eq('id',u.data.user.id).single();if(p.error||!p.data||p.data.status!=='active'||!['owner','admin'].includes(String(p.data.role)))throw new Error('FORBIDDEN');return p.data}
async function vaultMap(names:string[]){const map=new Map<string,string>();if(!names.length)return map;const r=await db.rpc('social_vault_get',{p_names:uniq(names)});if(!r.error)for(const x of r.data||[])if(x.secret_name&&x.secret_value)map.set(String(x.secret_name),String(x.secret_value));return map}
async function credsFor(provider:string){const d=PROVIDERS[provider];if(!d)return new Map<string,string>();const m=await vaultMap(d.credential_names);for(const n of d.credential_names){const e=Deno.env.get(n);if(e)m.set(n,e)}return m}
async function configured(provider:string){const d=PROVIDERS[provider];if(!d)return false;const m=await credsFor(provider);return d.credential_names.every((n:string)=>Boolean(m.get(n)))}
function callback(provider:string){return provider==='tiktok'?`${SUPABASE_URL}/functions/v1/social-tiktok-callback`:`${fnBase}?provider=${enc(provider)}&callback=1`}
async function saveState(userId:string,provider:string,returnUrl:string,metadata:any={}){const state=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');const r=await db.from('social_oauth_states').insert({state,user_id:userId,provider,return_url:returnUrl,expires_at:new Date(Date.now()+10*60*1000).toISOString(),metadata});if(r.error)throw r.error;return state}
async function setConn(platform:string,row:any){const r=await db.from('social_connections').upsert({platform,connection_mode:'oauth',updated_at:now(),...row},{onConflict:'platform'});if(r.error)throw r.error}
async function storeToken(platform:string,userId:string,token:any,externalId:string|null,metadata:any={}){const old=await db.from('social_oauth_tokens').select('refresh_token').eq('platform',platform).eq('user_id',userId).maybeSingle();const r=await db.from('social_oauth_tokens').upsert({platform,user_id:userId,external_account_id:externalId,access_token:token.access_token,refresh_token:token.refresh_token||old.data?.refresh_token||null,token_type:token.token_type||'Bearer',scopes:Array.isArray(token.scopes)?token.scopes:csv(token.scope),expires_at:token.expires_in?new Date(Date.now()+Number(token.expires_in)*1000).toISOString():null,refresh_expires_at:token.refresh_expires_in?new Date(Date.now()+Number(token.refresh_expires_in)*1000).toISOString():null,metadata,updated_at:now()},{onConflict:'platform,user_id'});if(r.error)throw r.error}
async function connected(platform:string,userId:string,token:any,externalId:string|null,accountName:string,metadata:any={}){await storeToken(platform,userId,token,externalId,metadata);await setConn(platform,{account_name:accountName,external_account_id:externalId,status:'connected',scopes:Array.isArray(token.scopes)?token.scopes:csv(token.scope),connected_by:userId,connected_at:now(),token_expires_at:token.expires_in?new Date(Date.now()+Number(token.expires_in)*1000).toISOString():null,last_verified_at:null,error_message:null,metadata})}
async function metaPermissions(userToken:string){const ver=Deno.env.get('META_GRAPH_VERSION')||'v26.0';try{const r=await fetch(`https://graph.facebook.com/${ver}/me/permissions?access_token=${enc(userToken)}`);const j=await r.json();if(!r.ok)return [];return (j.data||[]).filter((x:any)=>x.status==='granted').map((x:any)=>String(x.permission))}catch{return []}}
async function metaConnectPage(userId:string,pageId:string,userToken:string){const ver=Deno.env.get('META_GRAPH_VERSION')||'v26.0';const r=await fetch(`https://graph.facebook.com/${ver}/me/accounts?fields=id,name,access_token,instagram_business_account{id,username,name,profile_picture_url}&access_token=${enc(userToken)}`);const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||'Unable to read Facebook Pages');const page=(j.data||[]).find((x:any)=>String(x.id)===String(pageId));if(!page)throw new Error('Selected Facebook Page not found');const scopes=await metaPermissions(userToken);await connected('facebook',userId,{access_token:page.access_token,scope:scopes.join(' ')},page.id,page.name,{provider:'meta',page_name:page.name});if(page.instagram_business_account?.id){const ig=page.instagram_business_account;await connected('instagram',userId,{access_token:page.access_token,scope:scopes.join(' ')},ig.id,ig.username||ig.name||'Instagram Professional',{provider:'meta',facebook_page_id:page.id,username:ig.username||null})}else await setConn('instagram',{status:'error',error_message:'No Instagram Business/Professional account is linked to the selected Facebook Page.',metadata:{provider:'meta',facebook_page_id:page.id}});return page}

function linkedinHeaders(token:string){return {Authorization:`Bearer ${token}`,'X-Restli-Protocol-Version':'2.0.0','Linkedin-Version':Deno.env.get('LINKEDIN_VERSION')||'202607','Content-Type':'application/json'}}
async function linkedinOrganizations(token:string){
 const q='https://api.linkedin.com/rest/organizationAcls?q=roleAssignee&state=APPROVED&count=100&projection=(elements*(*,organization~(localizedName,vanityName)))';
 const r=await fetch(q,{headers:linkedinHeaders(token)});const j=await r.json();if(!r.ok)throw new Error(j?.message||`Unable to read LinkedIn Company Pages (${r.status})`);
 const out:any[]=[];for(const e of j.elements||[]){const urn=String(e.organization||e.organizationTarget||'');if(!urn.startsWith('urn:li:organization:'))continue;const id=urn.split(':').pop()||'';const name=e['organization~']?.localizedName||e['organization~']?.vanityName||urn;if(!out.some(x=>x.id===id))out.push({id,urn,name,role:e.role||null})}return out
}
async function linkedinConnectOrg(userId:string,orgId:string,token:any,scopes:string[]){
 const id=String(orgId).replace(/^urn:li:organization:/,'');if(!/^\d+$/.test(id))throw new Error('Invalid LinkedIn organization id');
 const r=await fetch(`https://api.linkedin.com/rest/organizations/${id}`,{headers:linkedinHeaders(token.access_token)});const org=await r.json();if(!r.ok)throw new Error(org?.message||`LinkedIn organization verification failed (${r.status})`);
 const name=org.localizedName||org.name?.localized?.[Object.keys(org.name?.localized||{})[0]]||`LinkedIn Organization ${id}`;
 await connected('linkedin',userId,{...token,scope:scopes.join(' ')},`urn:li:organization:${id}`,name,{provider:'linkedin',organization_id:id,vanity_name:org.vanityName||null,organization_verified:true});return org
}



async function providerApproval(provider:string){const r=await db.from('social_provider_approval_status').select('*').eq('provider',provider).maybeSingle();return r.data||{provider,app_review_status:'not_submitted',posting_audit_status:'not_submitted'}}
async function refreshTikTokTokenIfNeeded(t:any,c:any){
 if(!t?.refresh_token)return t;const exp=t.expires_at?new Date(t.expires_at).getTime():0;if(exp>Date.now()+15*60*1000)return t;
 const cr=await credsFor('tiktok');const key=cr.get('TIKTOK_CLIENT_KEY'),secret=cr.get('TIKTOK_CLIENT_SECRET');if(!key||!secret)return t;
 const rr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Cache-Control':'no-cache'},body:new URLSearchParams({client_key:key,client_secret:secret,grant_type:'refresh_token',refresh_token:t.refresh_token})});
 const rt=await rr.json();if(!rr.ok||rt.error)return t;await storeToken('tiktok',c.connected_by,rt,c.external_account_id,{...(t.metadata||{}),provider:'tiktok',refreshed_at:now()});await setConn('tiktok',{token_expires_at:rt.expires_in?new Date(Date.now()+Number(rt.expires_in)*1000).toISOString():null,scopes:csv(rt.scope),error_message:null});return (await tokenFor('tiktok',c))||t
}

async function capability(platform:string){const r=await db.from('social_platform_capabilities').select('*').eq('platform',platform).maybeSingle();return r.data||{platform,organic_publish_supported:false,engagement_metrics_supported:false,comment_read_supported:false,comment_reply_supported:false,required_publish_scopes:[],required_engagement_scopes:[],required_comment_scopes:[]}}
async function connection(platform:string){const r=await db.from('social_connections').select('*').eq('platform',platform).maybeSingle();return r.data||{platform,status:'not_connected',scopes:[]}}
async function tokenFor(platform:string,c:any){const userId=c?.connected_by;if(!userId)return null;const r=await db.from('social_oauth_tokens').select('*').eq('platform',platform).eq('user_id',userId).maybeSingle();return r.data||null}
async function metaUserToken(c:any){const userId=c?.connected_by;if(!userId)return null;const r=await db.from('social_oauth_tokens').select('*').eq('platform','meta_user').eq('user_id',userId).maybeSingle();return r.data||null}
function scopeResult(cap:any,granted:string[]){const req=uniq([...(cap.required_publish_scopes||[]),...(cap.required_engagement_scopes||[]),...(cap.required_comment_scopes||[])]);const missing=req.filter((x:string)=>!granted.includes(x));return {required:req,missing,ok:missing.length===0}}
async function saveVerification(platform:string,actorId:string,result:any){const r=await db.from('social_connection_verifications').upsert({platform,status:result.status,professional_ready:result.professional_ready,token_ok:result.token_ok,identity_ok:result.identity_ok,publish_ok:result.publish_ok,engagement_ok:result.engagement_ok,comments_read_ok:result.comments_read_ok,comments_reply_ok:result.comments_reply_ok,required_scopes_ok:result.required_scopes_ok,account_name:result.account_name||null,external_account_id:result.external_account_id||null,granted_scopes:result.granted_scopes||[],missing_scopes:result.missing_scopes||[],details:result.details||{},verified_at:result.verified_at||now(),verified_by:actorId,updated_at:now()},{onConflict:'platform'}).select('*').single();if(r.error)throw r.error;return r.data}
async function verifyPlatform(platform:string,actorId:string){const c=await connection(platform),cap=await capability(platform);if(c.status!=='connected'){return saveVerification(platform,actorId,{status:'not_connected',professional_ready:false,token_ok:false,identity_ok:false,publish_ok:false,engagement_ok:false,comments_read_ok:false,comments_reply_ok:false,required_scopes_ok:false,granted_scopes:[],missing_scopes:uniq([...(cap.required_publish_scopes||[]),...(cap.required_engagement_scopes||[]),...(cap.required_comment_scopes||[])]),details:{reason:c.error_message||'Account not connected'},verified_at:now()})}
 let t=await tokenFor(platform,c);if(platform==='tiktok'&&t)t=await refreshTikTokTokenIfNeeded(t,c);if(!t?.access_token){return saveVerification(platform,actorId,{status:'failed',professional_ready:false,token_ok:false,identity_ok:false,publish_ok:false,engagement_ok:false,comments_read_ok:false,comments_reply_ok:false,required_scopes_ok:false,account_name:c.account_name,external_account_id:c.external_account_id,granted_scopes:[],missing_scopes:uniq([...(cap.required_publish_scopes||[]),...(cap.required_engagement_scopes||[]),...(cap.required_comment_scopes||[])]),details:{reason:'Server token missing'},verified_at:now()})}
 const expired=Boolean(t.expires_at&&new Date(t.expires_at).getTime()<=Date.now()+30000);let identity_ok=false,api:any={},granted=csv(t.scopes||c.scopes),extra:any={};
 try{
  if(platform==='facebook'){const mu=await metaUserToken(c);if(mu?.access_token)granted=uniq([...granted,...await metaPermissions(mu.access_token)]);const ver=Deno.env.get('META_GRAPH_VERSION')||'v26.0';const r=await fetch(`https://graph.facebook.com/${ver}/${enc(c.external_account_id)}?fields=id,name&access_token=${enc(t.access_token)}`);api=await r.json();identity_ok=r.ok&&String(api.id||'')===String(c.external_account_id||'')}
  else if(platform==='instagram'){const mu=await metaUserToken(c);if(mu?.access_token)granted=uniq([...granted,...await metaPermissions(mu.access_token)]);const ver=Deno.env.get('META_GRAPH_VERSION')||'v26.0';const r=await fetch(`https://graph.facebook.com/${ver}/${enc(c.external_account_id)}?fields=id,username,name&access_token=${enc(t.access_token)}`);api=await r.json();identity_ok=r.ok&&String(api.id||'')===String(c.external_account_id||'')}
  else if(platform==='tiktok'){const r=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url,follower_count,following_count,likes_count,video_count',{headers:{Authorization:`Bearer ${t.access_token}`}});api=await r.json();const me=api?.data?.user||{};identity_ok=r.ok&&(!c.external_account_id||String(me.open_id||'')===String(c.external_account_id));extra.stats_probe_ok=r.ok&&['follower_count','following_count','likes_count','video_count'].every(k=>typeof me[k]==='number');extra.account_stats={follower_count:me.follower_count??null,following_count:me.following_count??null,likes_count:me.likes_count??null,video_count:me.video_count??null};if(granted.includes('video.list')){const vr=await fetch('https://open.tiktokapis.com/v2/video/list/?fields=id,create_time,title,like_count,comment_count,share_count,view_count',{method:'POST',headers:{Authorization:`Bearer ${t.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({max_count:20})});const vj=await vr.json();const vids=vj?.data?.videos||[];extra.video_metrics_status=vr.status;extra.video_metrics_probe_ok=vr.ok&&(!vj?.error?.code||vj.error.code==='ok');extra.video_sample_count=vids.length;extra.recent_video_metrics=vids.reduce((a:any,v:any)=>({views:a.views+Number(v.view_count||0),likes:a.likes+Number(v.like_count||0),comments:a.comments+Number(v.comment_count||0),shares:a.shares+Number(v.share_count||0)}),{views:0,likes:0,comments:0,shares:0})}if(granted.includes('video.publish')){const cr=await fetch('https://open.tiktokapis.com/v2/post/publish/creator_info/query/',{method:'POST',headers:{Authorization:`Bearer ${t.access_token}`,'Content-Type':'application/json; charset=UTF-8'}});const cj=await cr.json();extra.creator_info_status=cr.status;extra.creator_info_ok=cr.ok;extra.privacy_level_options=cj?.data?.privacy_level_options||[]}const approval=await providerApproval('tiktok');extra.app_review_status=approval.app_review_status;extra.posting_audit_status=approval.posting_audit_status;extra.private_test_post_ready=extra.creator_info_ok===true;extra.public_post_ready=extra.creator_info_ok===true&&approval.posting_audit_status==='approved'}
  else if(platform==='linkedin'){const orgId=String(c.metadata?.organization_id||c.external_account_id||'').replace(/^urn:li:organization:/,'');if(/^\d+$/.test(orgId)){const r=await fetch(`https://api.linkedin.com/rest/organizations/${orgId}`,{headers:linkedinHeaders(t.access_token)});api=await r.json();identity_ok=r.ok&&String(api.id||'')===orgId;extra.organization_verified=identity_ok;extra.organization_status=r.status;if(identity_ok&&granted.includes('r_organization_social')){const urn=enc(`urn:li:organization:${orgId}`);const er=await fetch(`https://api.linkedin.com/rest/organizationalEntityShareStatistics?q=organizationalEntity&organizationalEntity=${urn}`,{headers:linkedinHeaders(t.access_token)});extra.engagement_status=er.status;extra.engagement_probe_ok=er.ok}}else{identity_ok=false;extra.identity_error='LinkedIn Company Page is not selected/verified'}}
  else if(platform==='youtube'){const r=await fetch('https://www.googleapis.com/youtube/v3/channels?part=id,snippet&mine=true',{headers:{Authorization:`Bearer ${t.access_token}`}});api=await r.json();const ch=api?.items?.[0];identity_ok=r.ok&&Boolean(ch?.id)&&(!c.external_account_id||String(ch.id)===String(c.external_account_id));if(identity_ok&&granted.includes('https://www.googleapis.com/auth/yt-analytics.readonly')){const endDate=new Date().toISOString().slice(0,10);const sd=new Date(Date.now()-7*86400000).toISOString().slice(0,10);const q=new URLSearchParams({ids:'channel==MINE',startDate:sd,endDate,metrics:'views'});const ar=await fetch(`https://youtubeanalytics.googleapis.com/v2/reports?${q.toString()}`,{headers:{Authorization:`Bearer ${t.access_token}`}});extra.analytics_status=ar.status;extra.analytics_ok=ar.ok}}
  else if(platform==='x'){const r=await fetch('https://api.x.com/2/users/me?user.fields=id,name,username',{headers:{Authorization:`Bearer ${t.access_token}`}});api=await r.json();const xId=api?.data?.id;identity_ok=r.ok&&Boolean(xId);if(identity_ok){const headers={Authorization:`Bearer ${t.access_token}`};const pr=await fetch(`https://api.x.com/2/users/${xId}/tweets?max_results=5&tweet.fields=created_at,public_metrics,conversation_id,referenced_tweets`,{headers});extra.engagement_status=pr.status;extra.engagement_probe_ok=pr.ok;const mr=await fetch(`https://api.x.com/2/users/${xId}/mentions?max_results=5&tweet.fields=created_at,public_metrics,conversation_id,referenced_tweets,author_id`,{headers});extra.mentions_status=mr.status;extra.mentions_probe_ok=mr.ok}}
  else if(platform==='threads'){const r=await fetch(`https://graph.threads.net/v1.0/me?fields=id,username,name&access_token=${enc(t.access_token)}`);api=await r.json();identity_ok=r.ok&&Boolean(api?.id)}
  else if(platform==='pinterest'){const r=await fetch('https://api.pinterest.com/v5/user_account',{headers:{Authorization:`Bearer ${t.access_token}`}});api=await r.json();identity_ok=r.ok&&Boolean(api?.id||api?.username)}
  else if(platform==='reddit'){const r=await fetch('https://oauth.reddit.com/api/v1/me',{headers:{Authorization:`Bearer ${t.access_token}`,'User-Agent':'AllshieldInsuranceGroup/1.0'}});api=await r.json();identity_ok=r.ok&&Boolean(api?.id)}
 }catch(e){extra.identity_error=e instanceof Error?e.message:String(e)}
 const sr=scopeResult(cap,granted);const token_ok=!expired&&Boolean(t.access_token);const automationSupported=Boolean(cap.organic_publish_supported||cap.engagement_metrics_supported||cap.comment_read_supported||cap.comment_reply_supported);
 let publish_ok=!cap.organic_publish_supported||sr.required.filter((s:string)=>(cap.required_publish_scopes||[]).includes(s)).every((s:string)=>granted.includes(s));
 if(platform==='tiktok'&&cap.organic_publish_supported&&granted.includes('video.publish'))publish_ok=publish_ok&&extra.creator_info_ok===true&&extra.posting_audit_status==='approved';
 const engagementScopes=cap.required_engagement_scopes||[];let engagement_ok=!cap.engagement_metrics_supported||engagementScopes.every((s:string)=>granted.includes(s));if(platform==='youtube'&&cap.engagement_metrics_supported)engagement_ok=engagement_ok&&extra.analytics_ok===true;if(platform==='linkedin'&&cap.engagement_metrics_supported)engagement_ok=engagement_ok&&extra.engagement_probe_ok===true;if(platform==='tiktok'&&cap.engagement_metrics_supported)engagement_ok=engagement_ok&&extra.stats_probe_ok===true&&extra.video_metrics_probe_ok===true;if(platform==='x'&&cap.engagement_metrics_supported)engagement_ok=engagement_ok&&extra.engagement_probe_ok===true;
 let comments_read_ok=!cap.comment_read_supported||(cap.required_comment_scopes||[]).every((s:string)=>granted.includes(s));
 if(platform==='x'&&cap.comment_read_supported)comments_read_ok=comments_read_ok&&extra.mentions_probe_ok===true;
 let comments_reply_ok=!cap.comment_reply_supported||(cap.required_comment_scopes||[]).every((s:string)=>granted.includes(s));
 if(platform==='x'&&cap.comment_reply_supported)comments_reply_ok=comments_reply_ok&&extra.mentions_probe_ok===true;
 const professional_ready=Boolean(automationSupported&&token_ok&&identity_ok&&sr.ok&&publish_ok&&engagement_ok&&comments_read_ok&&comments_reply_ok);
 const status=professional_ready?'verified':token_ok&&identity_ok?'partial':'failed';
 const result=await saveVerification(platform,actorId,{status,professional_ready,token_ok,identity_ok,publish_ok,engagement_ok,comments_read_ok,comments_reply_ok,required_scopes_ok:sr.ok,account_name:c.account_name,external_account_id:c.external_account_id,granted_scopes:granted,missing_scopes:sr.missing,details:{automation_supported:automationSupported,provider_identity:api&&typeof api==='object'?api:{},token_expires_at:t.expires_at||null,...extra},verified_at:now()});
 if(token_ok&&identity_ok)await setConn(platform,{last_verified_at:now(),error_message:professional_ready?null:(sr.missing.length?`Connected, but missing professional permissions: ${sr.missing.join(', ')}`:null)});
 return result}

async function dashboard(){const conns=(await db.from('social_connections').select('*').order('platform')).data||[];const caps=(await db.from('social_platform_capabilities').select('*').order('platform')).data||[];const verifs=(await db.from('social_connection_verifications').select('*').order('platform')).data||[];const providers:any={};for(const [k,d] of Object.entries(PROVIDERS) as any){const m=await credsFor(k);providers[k]={key:k,label:d.label,platforms:d.platforms,configured:d.credential_names.every((n:string)=>Boolean(m.get(n))),fields:d.fields,credential_names:d.credential_names,oauth_supported:Boolean(d.oauth),manual_setup:Boolean(d.manual),managed_via:d.managed_via||null,callback_url:callback(k),guide:d.guide,links:d.links||[],approval:await providerApproval(k)}}
 const core=['facebook','instagram','tiktok','linkedin','youtube','x'];const vm=new Map(verifs.map((x:any)=>[x.platform,x]));const coreReady=core.filter(p=>vm.get(p)?.professional_ready).length;return {build:BUILD,providers,connections:conns,capabilities:caps,verifications:verifs,summary:{connected:conns.filter((x:any)=>x.status==='connected').length,verified:verifs.filter((x:any)=>x.status==='verified').length,professional_ready:verifs.filter((x:any)=>x.professional_ready).length,core_ready:coreReady,core_total:core.length,core_platforms:core,maya_can_operate_core:coreReady===core.length}}}

async function callbackHandler(req:Request,u:URL,provider:string){const state=u.searchParams.get('state')||'',code=u.searchParams.get('code')||'',err=u.searchParams.get('error_description')||u.searchParams.get('error')||'';const stR=await db.from('social_oauth_states').select('*').eq('state',state).eq('provider',provider).gt('expires_at',now()).maybeSingle();const st=stR.data;if(!st)return new Response('Invalid or expired OAuth state',{status:400});await db.from('social_oauth_states').delete().eq('state',state);const ret=safeReturn(st.return_url);if(err||!code)return Response.redirect(ret+`${ret.includes('?')?'&':'?'}social_oauth=error&provider=${enc(provider)}&message=${enc(err||'Authorization denied')}`,302);const c=await credsFor(provider);const redirect=callback(provider);
 if(provider==='meta'){const app=c.get('META_APP_ID')!,secret=c.get('META_APP_SECRET')!,ver=Deno.env.get('META_GRAPH_VERSION')||'v26.0';const tr=await fetch(`https://graph.facebook.com/${ver}/oauth/access_token?client_id=${enc(app)}&redirect_uri=${enc(redirect)}&client_secret=${enc(secret)}&code=${enc(code)}`);const tj=await tr.json();if(!tr.ok)throw new Error(tj?.error?.message||'Meta token exchange failed');const lr=await fetch(`https://graph.facebook.com/${ver}/oauth/access_token?grant_type=fb_exchange_token&client_id=${enc(app)}&client_secret=${enc(secret)}&fb_exchange_token=${enc(tj.access_token)}`);const lj=await lr.json();const userToken=lr.ok&&lj.access_token?lj.access_token:tj.access_token;const scopes=await metaPermissions(userToken);await storeToken('meta_user',st.user_id,{access_token:userToken,expires_in:lj.expires_in||tj.expires_in,scope:scopes.join(' ')},null,{provider:'meta'});const pr=await fetch(`https://graph.facebook.com/${ver}/me/accounts?fields=id,name,instagram_business_account{id,username,name}&access_token=${enc(userToken)}`);const pj=await pr.json();if(!pr.ok)throw new Error(pj?.error?.message||'Unable to list Facebook Pages');const pages=pj.data||[];if(pages.length===1)await metaConnectPage(st.user_id,pages[0].id,userToken);else{await setConn('facebook',{status:'needs_selection',connected_by:st.user_id,error_message:null,metadata:{provider:'meta',page_choices:pages.map((p:any)=>({id:p.id,name:p.name,instagram_username:p.instagram_business_account?.username||null}))}});await setConn('instagram',{status:'needs_selection',connected_by:st.user_id,error_message:null,metadata:{provider:'meta'}})}}
 else if(provider==='tiktok'){const tr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:c.get('TIKTOK_CLIENT_KEY')!,client_secret:c.get('TIKTOK_CLIENT_SECRET')!,code,grant_type:'authorization_code',redirect_uri:redirect})});const t=await tr.json();if(!tr.ok||t.error)throw new Error(t?.error_description||t?.message||'TikTok token exchange failed');const ir=await fetch('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url,follower_count,following_count,likes_count,video_count',{headers:{Authorization:`Bearer ${t.access_token}`}});const ij=await ir.json();const me=ij?.data?.user||{};await connected('tiktok',st.user_id,t,t.open_id||me.open_id||null,me.display_name||'TikTok',{provider:'tiktok',avatar_url:me.avatar_url||null,follower_count:me.follower_count??null,video_count:me.video_count??null})}
 else if(provider==='linkedin'){const tr=await fetch('https://www.linkedin.com/oauth/v2/accessToken',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code,client_id:c.get('LINKEDIN_CLIENT_ID')!,client_secret:c.get('LINKEDIN_CLIENT_SECRET')!,redirect_uri:redirect})});const t=await tr.json();if(!tr.ok)throw new Error(t?.error_description||t?.error||'LinkedIn token exchange failed');const scopes=csv(t.scope||'openid profile r_organization_admin r_organization_social w_organization_social r_organization_social_feed w_organization_social_feed');await storeToken('linkedin_user',st.user_id,{...t,scope:scopes.join(' ')},null,{provider:'linkedin'});const orgs=await linkedinOrganizations(t.access_token);if(orgs.length===1)await linkedinConnectOrg(st.user_id,orgs[0].id,t,scopes);else if(orgs.length>1)await setConn('linkedin',{status:'needs_selection',connected_by:st.user_id,error_message:null,scopes,metadata:{provider:'linkedin',organization_choices:orgs}});else await setConn('linkedin',{status:'error',connected_by:st.user_id,error_message:'No approved LinkedIn Company Page role was found for this member.',scopes,metadata:{provider:'linkedin'}})}
 else if(provider==='youtube'){const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:c.get('YOUTUBE_CLIENT_ID')!,client_secret:c.get('YOUTUBE_CLIENT_SECRET')!,redirect_uri:redirect,grant_type:'authorization_code'})});const t=await tr.json();if(!tr.ok)throw new Error(t?.error_description||t?.error||'Google token exchange failed');const ir=await fetch('https://www.googleapis.com/youtube/v3/channels?part=id,snippet&mine=true',{headers:{Authorization:`Bearer ${t.access_token}`}});const j=await ir.json();if(!ir.ok)throw new Error(j?.error?.message||'Unable to read YouTube channel');const ch=j.items?.[0];await connected('youtube',st.user_id,t,ch?.id||null,ch?.snippet?.title||'YouTube',{provider:'google',thumbnail:ch?.snippet?.thumbnails?.default?.url||null})}
 else if(provider==='x'){const verifier=String(st.metadata?.code_verifier||'');const tr=await fetch('https://api.x.com/2/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Authorization:basic(c.get('X_CLIENT_ID')!,c.get('X_CLIENT_SECRET')!)},body:new URLSearchParams({code,grant_type:'authorization_code',redirect_uri:redirect,code_verifier:verifier})});const t=await tr.json();if(!tr.ok)throw new Error(t?.error_description||t?.error||'X token exchange failed');const ir=await fetch('https://api.x.com/2/users/me?user.fields=id,name,username',{headers:{Authorization:`Bearer ${t.access_token}`}});const me=await ir.json();if(!ir.ok)throw new Error(me?.detail||'Unable to read X profile');await connected('x',st.user_id,t,me?.data?.id||null,me?.data?.username?`@${me.data.username}`:(me?.data?.name||'X'),{provider:'x',username:me?.data?.username||null})}
 else if(provider==='threads'){const tr=await fetch('https://graph.threads.net/oauth/access_token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.get('THREADS_APP_ID')!,client_secret:c.get('THREADS_APP_SECRET')!,grant_type:'authorization_code',redirect_uri:redirect,code})});const t=await tr.json();if(!tr.ok)throw new Error(t?.error?.message||t?.error_message||'Threads token exchange failed');let token=t.access_token,expires=t.expires_in;try{const lr=await fetch(`https://graph.threads.net/access_token?grant_type=th_exchange_token&client_secret=${enc(c.get('THREADS_APP_SECRET')!)}&access_token=${enc(token)}`);const lj=await lr.json();if(lr.ok&&lj.access_token){token=lj.access_token;expires=lj.expires_in||expires}}catch{}const ir=await fetch(`https://graph.threads.net/v1.0/me?fields=id,username,name&access_token=${enc(token)}`);const me=await ir.json();if(!ir.ok)throw new Error(me?.error?.message||'Unable to read Threads profile');await connected('threads',st.user_id,{access_token:token,expires_in:expires,scope:'threads_basic threads_content_publish'},me.id||null,me.username?`@${me.username}`:(me.name||'Threads'),{provider:'threads'})}
 else if(provider==='pinterest'){const tr=await fetch('https://api.pinterest.com/v5/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Authorization:basic(c.get('PINTEREST_APP_ID')!,c.get('PINTEREST_APP_SECRET')!)},body:new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:redirect})});const t=await tr.json();if(!tr.ok)throw new Error(t?.message||t?.error||'Pinterest token exchange failed');const ir=await fetch('https://api.pinterest.com/v5/user_account',{headers:{Authorization:`Bearer ${t.access_token}`}});const me=await ir.json();if(!ir.ok)throw new Error(me?.message||'Unable to read Pinterest account');await connected('pinterest',st.user_id,t,me.id||me.username||null,me.username?`@${me.username}`:'Pinterest',{provider:'pinterest'})}
 else if(provider==='reddit'){const tr=await fetch('https://www.reddit.com/api/v1/access_token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Authorization:basic(c.get('REDDIT_CLIENT_ID')!,c.get('REDDIT_CLIENT_SECRET')!),'User-Agent':'AllshieldInsuranceGroup/1.0'},body:new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:redirect})});const t=await tr.json();if(!tr.ok||t.error)throw new Error(t?.error||'Reddit token exchange failed');const ir=await fetch('https://oauth.reddit.com/api/v1/me',{headers:{Authorization:`Bearer ${t.access_token}`,'User-Agent':'AllshieldInsuranceGroup/1.0'}});const me=await ir.json();if(!ir.ok)throw new Error(me?.message||'Unable to read Reddit account');await connected('reddit',st.user_id,t,me.id||null,me.name?`u/${me.name}`:'Reddit',{provider:'reddit'})}
 else throw new Error('Unsupported OAuth provider');
 return Response.redirect(ret+`${ret.includes('?')?'&':'?'}social_oauth=success&provider=${enc(provider)}`,302)
}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const u=new URL(req.url),provider=u.searchParams.get('provider')||'';if(req.method==='GET'&&u.searchParams.get('callback')==='1')return await callbackHandler(req,u,provider);if(req.method!=='POST')return json({error:'Method not allowed'},405);const a=await actor(req);const b=await req.json();const action=String(b.action||'status');
 if(action==='status')return json({ok:true,...await dashboard()});
 if(action==='save_credentials'){const p=String(b.provider||'');const d=PROVIDERS[p];if(!d)return json({error:'Unknown provider'},400);const values=b.values&&typeof b.values==='object'?b.values:{};let saved=0;for(const n of d.credential_names){const v=String(values[n]||'').trim();if(!v)continue;const r=await db.rpc('social_vault_upsert',{p_name:n,p_value:v,p_description:`ALLSHIELD social provider credential for ${d.label}`});if(r.error)throw r.error;saved++}return json({ok:true,saved,provider:p,configured:await configured(p),message:saved?'Credentials encrypted in Supabase Vault.':'No credential values were submitted.'})}
 if(action==='set_provider_approval_status'){const p=String(b.provider||'');if(p!=='tiktok')return json({error:'Approval tracking is not enabled for this provider'},400);const allowed=new Set(['not_submitted','submitted','approved','rejected','changes_requested']);const app=String(b.app_review_status||'not_submitted'),audit=String(b.posting_audit_status||'not_submitted');if(!allowed.has(app)||!allowed.has(audit))return json({error:'Invalid approval status'},400);const r=await db.from('social_provider_approval_status').upsert({provider:p,app_review_status:app,posting_audit_status:audit,notes:String(b.notes||'').slice(0,2000)||null,updated_by:a.id,updated_at:now()},{onConflict:'provider'}).select('*').single();if(r.error)throw r.error;return json({ok:true,approval:r.data,message:'TikTok review status saved. Run Verify again after any approval change.'})}
 if(action==='guide'){const p=String(b.provider||'');const d=PROVIDERS[p];if(!d)return json({error:'Unknown provider'},400);return json({ok:true,provider:p,label:d.label,configured:await configured(p),callback_url:callback(p),guide:d.guide,fields:d.fields,manual_setup:Boolean(d.manual),managed_via:d.managed_via||null})}
 if(action==='assistant'){const d=await dashboard();const p=String(b.provider||'');const providerRow=p?d.providers[p]:null;let next:any[]=[];if(providerRow){const platforms=providerRow.platforms||[];const c=platforms.map((x:string)=>d.connections.find((y:any)=>y.platform===x));const v=platforms.map((x:string)=>d.verifications.find((y:any)=>y.platform===x));if(!providerRow.configured)next.push('Enter the provider developer credentials in this Connection Center and save them securely.');else if(c.some((x:any)=>!x||x.status!=='connected'))next.push(`Click Connect ${providerRow.label} and complete the provider authorization screen.`);else if(v.some((x:any)=>!x||!x.professional_ready))next.push('Run Verify. If verification is partial, use the missing-permissions list to update provider app access/scopes, then reconnect.');else next.push(`${providerRow.label} is professionally verified. Maya/Victor can rely on this connection for the capabilities Allshield has certified.`)}else{if(d.summary.core_ready<d.summary.core_total)next.push(`Finish the ${d.summary.core_total-d.summary.core_ready} remaining core professional connections.`);else next.push('Core social connections are verified. The next gate is Maya autonomous organic-posting and comment-response certification.')}return json({ok:true,mode:Deno.env.get('OPENAI_API_KEY')?'ai_available':'structured_setup_assistant',summary:d.summary,next_actions:next})}
 if(action==='start'){const p=String(b.provider||'');const d=PROVIDERS[p];if(!d)return json({error:'Unknown provider'},400);if(!d.oauth)return json({error:`${d.label} is manual/not yet automated in this connection layer.`,setup_required:true,guide:d.guide},409);if(!await configured(p))return json({error:`${d.label} developer credentials are not configured.`,setup_required:true,callback_url:callback(p),fields:d.fields},409);const ret=safeReturn(String(b.return_url||req.headers.get('origin')||''));let metadata:any={},state='';if(p==='x'){const k=await pkce();metadata.code_verifier=k.verifier;state=await saveState(a.id,p,ret,metadata);const c=await credsFor(p);const q=new URLSearchParams({response_type:'code',client_id:c.get('X_CLIENT_ID')!,redirect_uri:callback(p),scope:'tweet.read users.read tweet.write offline.access',state,code_challenge:k.challenge,code_challenge_method:'S256'});return json({ok:true,authorization_url:`https://x.com/i/oauth2/authorize?${q.toString()}`})}state=await saveState(a.id,p,ret,metadata);const c=await credsFor(p);
  if(p==='meta'){const scope='pages_show_list,pages_read_engagement,pages_manage_posts,pages_read_user_content,pages_manage_engagement,instagram_basic,instagram_content_publish,instagram_manage_comments';return json({ok:true,authorization_url:`https://www.facebook.com/${Deno.env.get('META_GRAPH_VERSION')||'v26.0'}/dialog/oauth?client_id=${enc(c.get('META_APP_ID')!)}&redirect_uri=${enc(callback(p))}&state=${enc(state)}&scope=${enc(scope)}&response_type=code`})}
  if(p==='tiktok'){const scope='user.info.basic,user.info.stats,video.list,video.publish,video.upload';return json({ok:true,authorization_url:`https://www.tiktok.com/v2/auth/authorize/?client_key=${enc(c.get('TIKTOK_CLIENT_KEY')!)}&scope=${enc(scope)}&response_type=code&redirect_uri=${enc(callback(p))}&state=${enc(state)}`})}
  if(p==='linkedin'){const q=new URLSearchParams({response_type:'code',client_id:c.get('LINKEDIN_CLIENT_ID')!,redirect_uri:callback(p),state,scope:'openid profile r_organization_admin r_organization_social w_organization_social r_organization_social_feed w_organization_social_feed'});return json({ok:true,authorization_url:`https://www.linkedin.com/oauth/v2/authorization?${q.toString()}`})}
  if(p==='youtube'){const scope='https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube.readonly https://www.googleapis.com/auth/youtube.force-ssl https://www.googleapis.com/auth/yt-analytics.readonly';const q=new URLSearchParams({client_id:c.get('YOUTUBE_CLIENT_ID')!,redirect_uri:callback(p),response_type:'code',scope,access_type:'offline',include_granted_scopes:'true',prompt:'consent',state});return json({ok:true,authorization_url:`https://accounts.google.com/o/oauth2/v2/auth?${q.toString()}`})}
  if(p==='threads'){const q=new URLSearchParams({client_id:c.get('THREADS_APP_ID')!,redirect_uri:callback(p),scope:'threads_basic,threads_content_publish',response_type:'code',state});return json({ok:true,authorization_url:`https://threads.net/oauth/authorize?${q.toString()}`})}
  if(p==='pinterest'){const q=new URLSearchParams({client_id:c.get('PINTEREST_APP_ID')!,redirect_uri:callback(p),response_type:'code',scope:'user_accounts:read,pins:read,pins:write,boards:read,boards:write',state});return json({ok:true,authorization_url:`https://www.pinterest.com/oauth/?${q.toString()}`})}
  if(p==='reddit'){const q=new URLSearchParams({client_id:c.get('REDDIT_CLIENT_ID')!,response_type:'code',state,redirect_uri:callback(p),duration:'permanent',scope:'identity submit read'});return json({ok:true,authorization_url:`https://www.reddit.com/api/v1/authorize?${q.toString()}`})}
 }
 if(action==='select_meta_page'){const pageId=String(b.page_id||'');const f=await connection('facebook');const userId=f.connected_by||a.id;const t=await db.from('social_oauth_tokens').select('access_token').eq('platform','meta_user').eq('user_id',userId).maybeSingle();if(!t.data?.access_token)return json({error:'Meta authorization must be completed first'},409);await metaConnectPage(userId,pageId,t.data.access_token);return json({ok:true})}
 if(action==='select_linkedin_org'){const orgId=String(b.organization_id||'');const lc=await connection('linkedin');const userId=lc.connected_by||a.id;const tr=await db.from('social_oauth_tokens').select('*').eq('platform','linkedin_user').eq('user_id',userId).maybeSingle();if(!tr.data?.access_token)return json({error:'LinkedIn authorization must be completed first'},409);const scopes=csv(tr.data.scopes);await linkedinConnectOrg(userId,orgId,tr.data,scopes);return json({ok:true})}
 if(action==='verify'){const platforms=Array.isArray(b.platforms)?b.platforms.map(String):[String(b.platform||'')].filter(Boolean);if(!platforms.length)return json({error:'Select a platform to verify'},400);const results=[];for(const p of platforms)results.push(await verifyPlatform(p,a.id));return json({ok:true,results,summary:(await dashboard()).summary})}
 if(action==='verify_all'){const platforms=(await db.from('social_connections').select('platform').order('platform')).data?.map((x:any)=>x.platform)||[];const results=[];for(const p of platforms)results.push(await verifyPlatform(p,a.id));return json({ok:true,results,summary:(await dashboard()).summary})}
 if(action==='disconnect'){const p=String(b.provider||'');const d=PROVIDERS[p];if(!d)return json({error:'Unknown provider'},400);for(const platform of d.platforms){const c=await connection(platform);if(c.connected_by)await db.from('social_oauth_tokens').delete().eq('platform',platform).eq('user_id',c.connected_by);await setConn(platform,{status:'not_connected',account_name:null,external_account_id:null,connected_by:null,connected_at:null,token_expires_at:null,last_verified_at:null,error_message:null,scopes:[],metadata:{}});await saveVerification(platform,a.id,{status:'not_connected',professional_ready:false,token_ok:false,identity_ok:false,publish_ok:false,engagement_ok:false,comments_read_ok:false,comments_reply_ok:false,required_scopes_ok:false,granted_scopes:[],missing_scopes:[],details:{reason:'Disconnected by Owner/Admin'},verified_at:now()})}if(p==='meta')await db.from('social_oauth_tokens').delete().eq('platform','meta_user');return json({ok:true})}
 return json({error:'Unknown action'},400)
 }catch(e){const m=e instanceof Error?e.message:String(e);return json({error:m,build:BUILD},m==='AUTH'?401:m==='FORBIDDEN'?403:500)}});