create table if not exists public.crm_contacts (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.coverage_leads(id) on delete set null,
  full_name text not null,
  email text,
  phone text,
  assigned_to uuid references public.profiles(id) on delete set null,
  status text not null default 'new' check (status in ('new','contacting','qualified','quoted','closed_won','closed_lost','do_not_contact')),
  source text not null default 'coverage_lead',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.crm_activities (
  id bigint generated by default as identity primary key,
  contact_id uuid not null references public.crm_contacts(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  activity_type text not null check (activity_type in ('note','call','email','sms','appointment','quote','status_change','assignment')),
  direction text check (direction in ('inbound','outbound','internal')),
  outcome text,
  details text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create table if not exists public.crm_tasks (
  id uuid primary key default gen_random_uuid(),
  contact_id uuid not null references public.crm_contacts(id) on delete cascade,
  assigned_to uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  title text not null,
  due_at timestamptz,
  status text not null default 'open' check (status in ('open','completed','cancelled')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists crm_contacts_lead_unique on public.crm_contacts(lead_id) where lead_id is not null;
create index if not exists crm_contacts_assigned_idx on public.crm_contacts(assigned_to,status);
create index if not exists crm_activities_contact_idx on public.crm_activities(contact_id,occurred_at desc);
create index if not exists crm_tasks_assigned_idx on public.crm_tasks(assigned_to,status,due_at);
alter table public.crm_contacts enable row level security;
alter table public.crm_activities enable row level security;
alter table public.crm_tasks enable row level security;
drop policy if exists crm_contacts_agent_read on public.crm_contacts;
create policy crm_contacts_agent_read on public.crm_contacts for select to authenticated using (assigned_to = auth.uid() or public.is_owner_or_admin());
drop policy if exists crm_contacts_admin_write on public.crm_contacts;
create policy crm_contacts_admin_write on public.crm_contacts for all to authenticated using (public.is_owner_or_admin()) with check (public.is_owner_or_admin());
drop policy if exists crm_activities_read on public.crm_activities;
create policy crm_activities_read on public.crm_activities for select to authenticated using (exists(select 1 from public.crm_contacts c where c.id=contact_id and (c.assigned_to=auth.uid() or public.is_owner_or_admin())));
drop policy if exists crm_activities_insert on public.crm_activities;
create policy crm_activities_insert on public.crm_activities for insert to authenticated with check (actor_id=auth.uid() and exists(select 1 from public.crm_contacts c where c.id=contact_id and (c.assigned_to=auth.uid() or public.is_owner_or_admin())));
drop policy if exists crm_tasks_read on public.crm_tasks;
create policy crm_tasks_read on public.crm_tasks for select to authenticated using (assigned_to=auth.uid() or created_by=auth.uid() or public.is_owner_or_admin());
drop policy if exists crm_tasks_write on public.crm_tasks;
create policy crm_tasks_write on public.crm_tasks for all to authenticated using (assigned_to=auth.uid() or created_by=auth.uid() or public.is_owner_or_admin()) with check (assigned_to=auth.uid() or created_by=auth.uid() or public.is_owner_or_admin());
revoke all on public.crm_contacts,public.crm_activities,public.crm_tasks from anon;
grant select,insert,update,delete on public.crm_contacts,public.crm_activities,public.crm_tasks to authenticated;
grant usage,select on sequence public.crm_activities_id_seq to authenticated;
insert into public.crm_contacts(lead_id,full_name,email,phone,status,source)
select l.id,l.full_name,l.email,l.phone,'new','coverage_lead'
from public.coverage_leads l
where not exists(select 1 from public.crm_contacts c where c.lead_id=l.id);

create or replace function public.sync_coverage_lead_to_crm() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.crm_contacts(lead_id,full_name,email,phone,status,source) values(new.id,new.full_name,new.email,new.phone,'new','coverage_lead') on conflict (lead_id) where lead_id is not null do nothing; return new; end $$;
drop trigger if exists trg_sync_coverage_lead_to_crm on public.coverage_leads;
create trigger trg_sync_coverage_lead_to_crm after insert on public.coverage_leads for each row execute function public.sync_coverage_lead_to_crm();
revoke all on function public.sync_coverage_lead_to_crm() from public,anon,authenticated;
