create table if not exists public.coverage_leads (
  id uuid primary key default gen_random_uuid(), full_name text not null, email text not null, phone text,
  coverage_type text not null, status text not null default 'new' check (status in ('new','contacted','qualified','closed','spam')),
  source text not null default 'website', assigned_to uuid references public.profiles(id) on delete set null,
  notes text, ip_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.career_applications (
  id uuid primary key default gen_random_uuid(), full_name text not null, email text not null, phone text,
  licensing_status text not null default 'not_licensed', resident_state char(2),
  status text not null default 'new' check (status in ('new','review','contacted','interview','approved','declined','converted','spam')),
  source text not null default 'careers_page', assigned_to uuid references public.profiles(id) on delete set null,
  converted_user_id uuid references public.profiles(id) on delete set null, converted_at timestamptz,
  notes text, ip_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.pipeline_activity (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('coverage_lead','career_application')),
  entity_id uuid not null, actor_id uuid references public.profiles(id) on delete set null,
  action text not null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists coverage_leads_created_at_idx on public.coverage_leads(created_at desc);
create index if not exists coverage_leads_status_idx on public.coverage_leads(status);
create index if not exists career_applications_created_at_idx on public.career_applications(created_at desc);
create index if not exists career_applications_status_idx on public.career_applications(status);
create index if not exists pipeline_activity_entity_idx on public.pipeline_activity(entity_type,entity_id,created_at desc);
create unique index if not exists career_applications_converted_user_unique on public.career_applications(converted_user_id) where converted_user_id is not null;
alter table public.coverage_leads enable row level security; alter table public.career_applications enable row level security; alter table public.pipeline_activity enable row level security;
drop policy if exists coverage_leads_admin_all on public.coverage_leads; create policy coverage_leads_admin_all on public.coverage_leads for all to authenticated using (public.is_owner_or_admin()) with check (public.is_owner_or_admin());
drop policy if exists career_applications_admin_all on public.career_applications; create policy career_applications_admin_all on public.career_applications for all to authenticated using (public.is_owner_or_admin()) with check (public.is_owner_or_admin());
drop policy if exists pipeline_activity_admin_all on public.pipeline_activity; create policy pipeline_activity_admin_all on public.pipeline_activity for all to authenticated using (public.is_owner_or_admin()) with check (public.is_owner_or_admin());
revoke all on public.coverage_leads,public.career_applications,public.pipeline_activity from anon;
grant select,insert,update,delete on public.coverage_leads,public.career_applications,public.pipeline_activity to authenticated;
grant usage,select on sequence public.pipeline_activity_id_seq to authenticated;