create table if not exists public.campaign_enrollments (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  agent_id uuid not null references public.profiles(id) on delete restrict,
  carrier text not null,
  external_order_ref text,
  customer_ref_hash text,
  submitted_at timestamptz not null default now(),
  qualified_at timestamptz,
  status text not null default 'submitted' check (status in ('submitted','qualified','needs_reconciliation','ineligible','cancelled')),
  card_orderable boolean not null default false,
  residual_eligible boolean not null default false,
  coverage_effective_date date,
  reconciliation_status text not null default 'not_started' check (reconciliation_status in ('not_started','needs_fix','verified','ineligible')),
  reconciliation_notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists campaign_enrollments_order_ref_unique on public.campaign_enrollments(campaign_id,external_order_ref) where external_order_ref is not null;
create index if not exists campaign_enrollments_agent_qualified_idx on public.campaign_enrollments(agent_id,qualified_at) where status='qualified';
create index if not exists campaign_enrollments_residual_idx on public.campaign_enrollments(campaign_id,residual_eligible,coverage_effective_date);
alter table public.campaign_enrollments enable row level security;
create policy campaign_enrollments_self_read on public.campaign_enrollments for select to authenticated using (agent_id=auth.uid() or public.is_owner_or_admin());
create policy campaign_enrollments_admin_write on public.campaign_enrollments for all to authenticated using (public.is_owner_or_admin()) with check (public.is_owner_or_admin());

create table if not exists public.comp_plan_change_log (
  id bigint generated by default as identity primary key,
  plan_version_id uuid not null references public.comp_plan_versions(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz not null default now()
);
alter table public.comp_plan_change_log enable row level security;
create policy comp_change_log_admin_read on public.comp_plan_change_log for select to authenticated using (public.is_owner_or_admin());
create policy comp_change_log_admin_insert on public.comp_plan_change_log for insert to authenticated with check (public.is_owner_or_admin());